### ISSUE TITLE
Request for node, ruby, and elixir repls. :)

### ISSUE THREAD

**Issue by megalithic** [hkupty/iron.nvim#1]
Neat project! Was wondering if you'd be up for adding a few more repls? (node, ruby/rails, and elixir)

Thanks!

**Comment by hkupty** [comment]
Sure!

I'll see if I can do that later today! 

I won't be able to create specific bindings or add special commands for those languages, though.

**Comment by hkupty** [comment]
It's done. This should provide basic functionality to those languages. If you miss anything, please tell!
Cheers
