### ISSUE TITLE
Unable to register as remote plugin

### ISSUE THREAD

**Issue by zegervdv** [hkupty/iron.nvim#10]
When running `:UpdateRemotePlugins` on a clean install iron is no longer registering as a remote plugin.
The issue started to occur on commit 547e35371ed7fe42cd39e8c39baf9ffc52adb4be.

**Comment by hkupty** [comment]
This seems to be related to how python-client deals with remote plugins (I figure) as it is yielding errors for other plugins as well (for exemple, as per neovim/neovim#4691). Nonetheless, I'll take a look to understand what caused this on irons side and try to circumvent that.

Meanwhile, you can call `:UpdateRemotePlugins` twice. Somehow, this 'fixes' the issue (iron gets available). Obviously this is not optimal, but still, this might help while this issue isn't fixed.

Thanks for reporting.
Cheers

**Comment by zegervdv** [comment]
Running `:UpdateRemotePlugins` twice doesn't seem to fix it.
It still cannot find the plugin or the iron commands.

**Comment by hkupty** [comment]
That is strange.. I've been unable to reproduce it here (even though `:UpdateRemotePlugins` is a bit unstable for me). Would you mind running neovim with `NVIM_PYTHON_LOG_FILE=foo nvim` and pasting the log on a gist?

**Comment by zegervdv** [comment]
There was not a lot of output:
~~~
2016-07-22 10:30:27,126 [INFO @ script_host.py:setup:52] 10823 - install import hook/path
2016-07-22 10:30:27,127 [INFO @ script_host.py:setup:57] 10823 - redirect sys.stdout and sys.stderr
2016-07-22 10:30:32,888 [INFO @ session.py:request:97] 10830 - 'Received error: [1, b'Key not found']
2016-07-22 10:30:32,890 [INFO @ session.py:request:97] 10830 - 'Received error: [1, b'Key not found']
~~~
This was all I got after starting neovim and running `:UpdateRemotePlugins`.

**Comment by Alok** [comment]
I'm getting a similar error. In my case, it stops `deoplete` from working, and that's a far more important plugin (no offense).

**Comment by hkupty** [comment]
I'm trying to fix that on the `testing` branch.

I'll probably need to find another way to log stuff as it seems that this
bug is caused by importing log..

**Comment by hkupty** [comment]
@zegervdv & @Alok : I just changed how I do logging and sent to master a code that I assume should fix. Later on I'll check again. Please post here after trying if this fixed or if the error still persists.

Thanks

**Comment by Alok** [comment]
Fixed it for me.

**Comment by hkupty** [comment]
@Alok Glad to here it. Hopefully iron.nvim will become as important as deoplete soon ;)

**Comment by hkupty** [comment]
After some time, it seems that the problem is solved. @zegervdv, if you still have the problem, feel free to reopen the issue.

**Comment by zegervdv** [comment]
The issue is solved for me as well. Thanks!

**Comment by hkupty** [comment]
Glad to hear it!
