### ISSUE TITLE
:IronRepl behavior request: stay in current buffer and not switch to insert mode

### ISSUE THREAD

**Issue by randomizedthinking** [hkupty/iron.nvim#113]
The default behavior of `:IronRepl` command is: start the repl, switch to the repl buffer, and start insert mode. The workflow seems not ideal: for people using a repl, mostly we'd prefer staying in the edit buffer and entering commands from there.

How do you think?

I can change the code, and would like to get people's opinions first.

**Comment by hkupty** [comment]
That makes sense. It should be very easy to focus on the repl right after if one wants to.

Thanks for the issue and for being open to improving iron!

**Comment by randomizedthinking** [comment]
Sounds good.. I will have a simple patch to the behavior updated.

**Comment by sheriferson** [comment]
Is there any way of achieving part of this right now? I like the focus staying in the file buffer, but I really don't want it to go into Insert mode automatically. I'm assuming not, but is there a way to not go into Insert mode?

**Comment by hkupty** [comment]
Every small bit of iron is written in a way that it can be reused or configured, so yes, it's doable. I didn't remember this issue and apparently it's not implemented yet. I'll come up with something to fix this.

**Comment by hhoeflin** [comment]
Created a pull request #139

**Comment by svenski** [comment]
Here is a (my) hacky way of making it stay in the buffer (note I have the repl opened to the right): 

    nmap <buffer> <localleader>rf :IronRepl<cr><Esc><C-w>h

**Comment by ExpandingMan** [comment]
For me it does seem to stay in the buffer by default, but it enters insert mode, which is really annoying.  Any way of turning this off?

**Comment by ExpandingMan** [comment]
Has anyone figured out how to prevent it from going into insert mode?  This is still driving me bananas.

**Comment by hkupty** [comment]
I've created a PR now (#159) which can be helpful I think. Let me know if it fixes for you as well or if it's still happening, @ExpandingMan

**Comment by ExpandingMan** [comment]
I actually was not having problem with the selection moving: it doesn't move on `master`, and it's not moving now on this PR.  My major complaint was that it would always go to insert mode when I start the REPL, and this it still does on this PR.

**Comment by hkupty** [comment]
@ExpandingMan Thanks for the feedback and I'm sorry I misunderstood your issue. It should be fixed now with the latest version. Let me know how it works for you :)

I'm sorry it took this long for me to actually fix the issue. Life sometimes gets in the way and it's really hard to keep up.

Best regards,
Henry

**Comment by ExpandingMan** [comment]
Ahhh, so much nicer, thanks!

No worries, I'm always so neglectful of my own projects I would be a dreadful hypocrite if I started criticizing others for being slow to make changes.

**Comment by hkupty** [comment]
Glad to know it's better now. I'm closing the issue.

Feel free to reopen or open a new one if something is not working.

Cheers,
Henry
