### ISSUE TITLE
documentation out of date: missing features from previous version

### ISSUE THREAD

**Issue by cmcaine** [hkupty/iron.nvim#121]
e.g. `E492: Not an editor command: IronPromptCommand`

Presumably this was lost with the rewrite to Lua. Personally, I used that command quite often for opening Repls on other machines or in abduco (like tmux/screen).

A good alternative for me would be if `IronRepl <arbitrary command line here>` worked

Anyway, the documentation should probably be updated. I don't have time to do either thing right now, but maybe I'll make time in the next little while if it annoys me too much ;)

From a quick look at the code, it seems that Repls can no longer be defined with variables in Vim. Maybe you expect that nobody wants to modify that kind of thing any more? Or we're expected to edit iron.fts with luaeval?

Cheers for iron.nvim, it helps me out a lot.

**Comment by hkupty** [comment]
Hi,

I'm very sorry for taking this long to answer.

My idea is that people could actually have more control over their repl definitions, though using the lua API.

I believe those features like prompt and provide commands should be easily done on the user side, as they're closer to individual/personal usage. My idea is to make iron closer to raw API, so people can extend it the way they want.

Also, I suggest that you take a look at [trex.nvim](https://github.com/Vigemus/trex.nvim/), as I might have implemented some features that allow better customization there.

Nonetheless, I'll leave two tasks open from this issue:
* Update the docs
* Document extensibility through lua API.

Best regards,
Henry

**Comment by hkupty** [comment]
I believe this issue can be closed now. Please let me know if you need any help setting up prompt or programatic-based decision for iron.

Best regards,
Henry

**Comment by hkupty** [comment]
Closing the issue. Don't refrain from reopening or creating a new one if you need :)
