### ISSUE TITLE
Do not move cursor?

### ISSUE THREAD

**Issue by urbainvaes** [hkupty/iron.nvim#152]
Hi Henry,

Consider the file
```python
import math

a = 1
b = 2
c = 3
|
```
where `|` indicates the position of the curson. In previous versions of the plugin (back when python was used), sending the motion `{` would result in
```python
a = 1
b = 2
c = 3
```
being sent to the REPL, and the cursor would stay fixed. With the latest versions of the plugin, the cursor moves according to the motion `{`. Is this desired and can this be prevented? It's especially disorienting when sending the motion `gg`.

Many thanks!

**Comment by hkupty** [comment]
Hi, I'm really sorry I couldn't look into your issue before.
I've been having a hard time keeping up w/ my projects at my current work situation, so I'm really sorry I let this one slip.

I plan on reworking some features of the plugin to be less intrusive, but I'm really out of time to do that now.

**Comment by urbainvaes** [comment]
Hi Henry!

No worry, and no need to apologise. :) Thanks for reopening the issue. I'd open a pull request if I was more familiar with the `lua` interface, but at the moment I'm not proficient with the language.

**Comment by hkupty** [comment]
Hi, sorry for the long delay (again), but I've managed to take a stab at both issues. Please check the pr I just opened to see if it fixes for you :)
