### ISSUE TITLE
Unwanted trigger of BufEnter in the terminal buffer

### ISSUE THREAD

**Issue by urbainvaes** [hkupty/iron.nvim#153]
Consider again the file:
```python
import math

a = 1
b = 2
c = 3
|
```

Steps to reproduce:
- Open an iPython shell with `IronRepl`,
- In the terminal buffer, run
```vim
autocmd BufEnter <buffer> echom "Hello, world!"
```
- Go back to the python file, with the cursor position as indicated above.
- Send the motion `{`.

You'll see that `Hello, world!` gets echoed, which is not the desired behavior. This case is innocuous, but the behavior can be quite disruptive with other autocommands.

In `viml`, adding `noautocmd` somewhere would probably fix the issue, but in `lua` I'm not too sure.

Many thanks again!

**Comment by hkupty** [comment]
I'll reopen this issue as it ties down to what I said in #152. It should definitely not trigger an autocmd there.

Once again, I'm sorry for not being able to keep it up.

**Comment by urbainvaes** [comment]
No worry, thanks for reopening.

**Comment by hkupty** [comment]
This should be closed with the PR merged. Let me know if it is working for you or if you're still having problems.

Sorry for the delay once again.

Best regards,
Henry
