### ISSUE TITLE
send filename of current buffer to REPL

### ISSUE THREAD

**Issue by daler** [hkupty/iron.nvim#155]
Thanks for this plugin!

I'm having trouble sending the filename of the current buffer over to the REPL. The use-case is when writing an RMarkdown file I'd like to send the equivalent of:

```r
rmarkdown::render("%")
```

to the REPL so that it renders the current document, such that the `%` is filled in as the filename of the RMarkdown file being edited.

`:IronSend! rmarkdown::render("%")` just sends a literal `%`, and I haven't been able to find a solution. Any advice appreciated.

**Comment by hkupty** [comment]
Hi, I'm sorry I missed your issue.

`IronSend` is a viml command that prepares plain string to be sent to the REPL through the lua interface.

You can call the lua interface directly like this:
```viml
:call luaeval("require('iron').core.send(_A[1], _A[2])", [&ft, "rmarkdown::render(".expand("%").")"])
" Maybe map that to a key
:map <F5> <Cmd>call luaeval("require('iron').core.send(_A[1], _A[2])", [&ft, "rmarkdown::render(".expand("%").")"])<CR>
```

**Comment by daler** [comment]
Ah! Thanks, I'll give it a shot.
