### ISSUE TITLE
[question] How can I open a REPL using a especific `repl_definition`?

### ISSUE THREAD

**Issue by m00qek** [hkupty/iron.nvim#158]
Hello, I have two `repl_definitions` for `clojure`: one for `leiningen` and one for `deps`. 
I know that I can change the config to point to the REPL I want to open:
```lua
iron.core.set_config {
  preferred = {
    clojure = "deps"
  }
}
```
but this changes the default for all `clojure` REPLs.
Is there a quick way to switch between definitions?

thanks

**Comment by hkupty** [comment]
Hi, thanks for the issue.
I was double-checking the code now and it seems iron is missing a function for invoking without relying on the preferred repl.

For now, I believe you can have some bindings, like:
`map <some binding> <cmd>lua "require('iron').core.set_config{preferred = {clojure = 'deps'}}"`
`map <other binding> <cmd>lua "require('iron').core.set_config{preferred = {clojure = 'leiningen'}}"`

This is obviously suboptimal, so I'll keep this issue open and provide a way to invoke directly.

If you use [impromptu.nvim](https://github.com/Vigemus/impromptu.nvim), you can use this function:
```lua
local iron = require("iron")
local impromptu = require("impromptu")

_G.spawn_repl = function(ft)
  if ft == nil then
    local cb = vim.api.nvim_get_current_buf()
    ft = vim.api.nvim_buf_get_option(cb, 'filetype')
  end
  local opts = {}
  local defs = iron.core.list_definitions_for_ft(ft)

  for _, kv in ipairs(defs) do
    local descr
    if type(kv[2].command) == "table" then
      descr = table.concat(kv[2].command, " ")
    else
      descr = kv[2].command
    end

    opts[kv[1]] = {
      description = descr,
      data = kv[2]
    }
  end

  impromptu.ask{
    question = "Select repl definition",
    options = opts,
    handler = function(session, opt)
      iron.ll.create_new_repl(ft, opt.data)
      trex.attach(ft)
      return true
    end
  }
```

**Comment by hkupty** [comment]
I just added a function(`iron.core.repl_by_name`) that takes the definition name and the optional filetype (resorting to current buffers filetype if none supplied).

I'm sorry it took so long to fix this.

Best regards,
Henry
