### ISSUE TITLE
Error flashes when sending visual selection

### ISSUE THREAD

**Issue by GCBallesteros** [hkupty/iron.nvim#168]
# System
Iron: commit 746f2...
Nvim: commit b9ceac46... (HEAD as of 24 September 2020)
REPL: ipython
OS: macOS Catalina 10.15.6

# Iron config (plugins.lua)
```lua
local iron = require('iron')

iron.core.set_config {
  preferred = {
    python = "ipython"
  }
}
```

# Issue
The following message flashes when sending a visual selection using the default bindings:
`E5108: Error executing lua /Users/garfield/.vim/plugged/iron.nvim/lua/iron/init.lua:377: Expected 4 arguments`

Despite the error message the visual selection is succesfully sent to the REPL and executed.

# Expected behaviour
The error message shouldn't flash.

Thanks!

**Comment by hkupty** [comment]
Thanks for the fix. Closing :)
