### ISSUE TITLE
sending code from nvim to R REPL garbled

### ISSUE THREAD

**Issue by danjenson** [hkupty/iron.nvim#171]
Sending code from nvim to the R REPL is all garbled and often depends on where your cursor is (and sometimes doesn't), so sending several highlighted lines works maybe 1 in 5 times.

NVIM v0.5.0-715-gc5ceefca7 (neovim-nightly AUR package)
Arch Linux

**Comment by danjenson** [comment]
Also gets a warning message from init.lua line 344 about expecting 4 arguments, but then it still sends it anyway..

**Comment by hkupty** [comment]
I guess this was related to #170. Can you double-check now after that PR was merged?

**Comment by danjenson** [comment]
Fixed
