### ISSUE TITLE
Bugs in the the new upgrades.

### ISSUE THREAD

**Issue by f3fora** [hkupty/iron.nvim#187]
After the last upgrades `repl_open_cmd = "topleft vertical 40 split"` do not work anymore in a configuration like:
```lua
local iron = require('iron')
iron.core.add_repl_definitions {lua = {lua51 = {command = {'lua5.1'}}}}

iron.core.set_config {
     preferred = {python = 'ipython', lua = 'lua51', sh = 'bash', cpp = 'root'},
     repl_open_cmd = "topleft vertical 40 split"
}
```

Reading that that function is deprecated in comments of the `iron.core`,  I moved to something like this:
```lua
iron.config = {
    preferred = {python = 'ipython', lua = 'lua51', sh = 'bash', cpp = 'root'},
}
```

This works. However if I set `iron.config.repl_open_cmd = something`, also the preferred do not works.

There's a typo here: https://github.com/hkupty/iron.nvim/blob/531dfdb0ef66858234b7115ebb938e829c954c0b/lua/iron/view.lua#L32

**Comment by hkupty** [comment]
Hi! thanks for the issue. I hadn't noticed that. Seems like I have to improve tests.

Anyway, should be fixed after merging #188.. Would you mind testing?

Best regards,
Henry

**Comment by f3fora** [comment]
These two configurations work: 
```lua
iron.core.set_config({
    preferred = {python = 'ipython', lua = 'lua51', sh = 'bash', cpp = 'root'},
     repl_open_cmd = "topleft vertical 40 split"
})
```
and
```lua
iron.config.preferred = {python = 'ipython', lua = 'lua51', sh = 'bash', cpp = 'root'}
iron.config.repl_open_cmd = "topleft vertical 40 split"
```

This one not:
```lua
iron.config = {
     preferred = {python = 'ipython', lua = 'lua51', sh = 'bash', cpp = 'root'},
     repl_open_cmd = "topleft vertical 40 split"
}

**Comment by hkupty** [comment]
Personally, I don't quite like `iron.config = { ... }` since there are multiple default values used by iron under the hood that are kept in the `config` object.

However, I'm open to discussing if it should be allowed or not.

**Comment by f3fora** [comment]
There's no documentation about it. So I just suppose how to use it. If it works as it should work, for me it's enough.  

Thanks for this wonderful plugin and for the help.

**Comment by hkupty** [comment]
Thanks! I'm super grateful by people enjoying the plugin. As long as it's useful and helpful, I'm happy :)
