### ISSUE TITLE
Getting attempt to index global 'iron' (a nil value) error from settings.

### ISSUE THREAD

**Issue by thepenguinthatwants** [hkupty/iron.nvim#191]
Hi, I was trying to use your plugin.
As having a repl should ease up life quite a lot.

On my main init.lua I added
require('iron')

And then inside the nvim/lua/iron/init.lua

```
local iron = require('iron')

iron.core.add_repl_definitions {
  python = {
    mycustom = {
      command = {"mycmd"}
    }
  },
  clojure = {
    lein_connect = {
      command = {"lein", "repl", ":connect"}
    }
  }
}

iron.core.set_config {
  preferred = {
    python = "ipython",
    clojure = "lein"
  }
}

```
And this is output from opening nvim up.
`E5113: Error while calling lua chunk: /home/penguin/.config/nvim/lua/iron/init.lua:1: attempt to index global 'iron' (a nil value)`

If I remove the local iron line I get

`E5113: Error while calling lua chunk: /home/penguin/.config/nvim/lua/iron/init.lua:1: loop or previous error loading module 'iron'`

**Comment by hkupty** [comment]
Hi! thanks for the issue...
I think what happens here is that you're shadowing the name `iron`, so neovim gets confused about whether should it load the plugin or should it load your config.. I suggest that under your neovim folder you create a `plugins` subdirectory so you can keep your configs there without conflicting w/ the plugin names, like this:

```lua
-- on init.lua
require("plugins.iron")
```

```lua
-- on nvim/lua/plugins/iron.lua
local iron = require("iron")

iron.core.add_repl_definitions{ ...  }
iron.core.set_config{ ... }
```

This way the path `iron` is unambiguously referring to the plugin and `plugins.iron` points directly to your configuration.

I hope this helps!

Best regards,
Henry John Kupty

**Comment by thepenguinthatwants** [comment]
Wow, I didn't even thought about neovim could get confused by the structure. 
Thanks for guiding!!

**Comment by hkupty** [comment]
Glad to help!
