### ISSUE TITLE
Any good ways to unbind certain defaults?

### ISSUE THREAD

**Issue by thepenguinthatwants** [hkupty/iron.nvim#192]
Hi,
Is there any options or ways to unbind these defaults as they crash with my other bindings.
```

   ctr              |<Plug>(iron-send-motion)|              `n`
   ctr              |<Plug>(iron-visual-send)|              `v`
   cp               |<Plug>(iron-repeat-cmd)|               `n`
   cst              |<Plug>(iron-interrupt)|                `n`
   cq               |<Plug>(iron-exit)|                     `n`
   cl               |<Plug>(iron-clear)|                    `n`
```

**Comment by hkupty** [comment]
Hi! Sorry for taking long to reply...

I don't think there's anything regarding the default maps, but I can make sure to fix that in the next batch of improvements.

**Comment by augustebaum** [comment]
Seconded, `cl` is mapping to `change left` in default Vim so not the best choice.

**Comment by hkupty** [comment]
You can set
```vim
  let g:iron_map_defaults = 0
  let g:iron_map_extended = 0
```

Then you can bind them however you like.
