### ISSUE TITLE
Option to toggle REPL

### ISSUE THREAD

**Issue by d-miketa** [hkupty/iron.nvim#198]
Hi and thanks for the plugin! It's been very useful. Would it be possible to add a toggle to hide and show the REPL window?

**Comment by hkupty** [comment]
It is already toggle-able. Calling `:IronRepl` or `lua require("iron.core").repl_for(vim.o.ft)` on a filetype that has a repl open will close it. If you call it again, it will re-open. It is the [default configuration](https://github.com/hkupty/iron.nvim/blob/master/lua/iron/defaults.lua#L9)

**Comment by d-miketa** [comment]
You’re absolutely right - I just never opened Iron using that command and so never noticed. Thank you!

**Comment by hkupty** [comment]
It was designed to be called from a keybinding and then sending stuff to repl, so the behavior made sense back then... then opening the repl and sending immediately was introduced, which sped up the workflow but this got a bit lost. :)


Best regards and amazing holidays,
Henry
