### ISSUE TITLE
Send text in Visual mode

### ISSUE THREAD

**Issue by jduc** [hkupty/iron.nvim#20]
Hey, 

Quick suggestion/question: often, it's convenient to select some text in visual mode and send it to the REPL rather than typing a motion. 

There is surely an easy mapping/implementation to do that but my knowledge in vim plugins is close to 0 (shame on me) and if it's fast for you, I would really appreciate a little help. 

What I did that kinda work for my ipython repl is: 
``vmap s <ESC>`>a<space><ESC>ctr`< ``
but as you can see, this adds a space at the end of the selection before sending otherwise it was sending the selected text minus the last character for some reason. 

As this "solution" is pretty clunky, would you have another suggestion or would it be possible to implement another mapping like the `ctr` but for visual mode ? 

Thanks a lot

**Comment by hkupty** [comment]
Hi!
That should be fairly easy to implement.. I'll take a look at that later on today.

Cheers,

**Comment by hkupty** [comment]
This commit (https://github.com/hkupty/iron.nvim/commit/bb6217990a68b22f1e83a2c0793ccb6e01c36d8f)  actually implements `ctr` on visual mode, so this should be closed by now.

Feel free to reopen the issue if something is not working.

Cheers!

**Comment by jduc** [comment]
Thanks a lot. I gave it a try but I encountered a small bug with multilines ipython and ptipython repl: when sending lines through visual, it is sending them multiple times depending on the number of lines sent . Here is an example code: 

```python
print("Hello")
print("World")
```

Sending these two lines via `ctr}` for instance prints

> Hello
> World 

on two lines as expected. Now sending via `v}ctr` prints: 


> Hello
> World
> Hello
> World

Now adding `print("!")` as a third line in the code and sending via visual mode prints out: 

> Hello
> World
> !
> Hello
> World
> !
> Hello
> World
> !
> 

Are you getting the same behavior ? Thanks again for being so responsive, really appreciate it.

**Comment by hkupty** [comment]
Ugh.. I tested this commit from another branch I'm working, `testing` and it did work fine. It seems that, since I've changed a bit how the logic works, backporting was not enough... I'll try to fix that.

Cheers

**Comment by hkupty** [comment]
I've merged the `testing` branch, which enhanced REPL management in several ways. It seems to solve this problem as well..

If the problem persists, don't refrain from reopening this issue!

Cheers!

**Comment by hkupty** [comment]
I've merged the `testing` branch, which enhanced REPL management in several ways. It seems to solve this problem as well..

If the problem persists, don't refrain from reopening this issue!

Cheers!

**Comment by jduc** [comment]
Thanks ! Unfortunately, it seems I'm unable update to the newer merge. Seems to be related to the zen submodule. Here is the error I get after the `UpdateRemotePlugins` command: 

```python
Encountered ModuleNotFoundError loading plugin at /home/user/.nvim/plugged/iron.nvim/rplugin/python3/iron: No module named 'zen'
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.6/site-packages/neovim/plugin/host.py", line 131, in _load
    module = imp.load_module(name, file, pathname, descr)
  File "/usr/lib/python3.6/imp.py", line 244, in load_module
    return load_package(name, filename)
  File "/usr/lib/python3.6/imp.py", line 216, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 675, in _load
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
ModuleNotFoundError: No module named 'zen'
```

**Comment by hkupty** [comment]
I'm sorry this has broken the update. It seems that it has not created the submodule.

Apparently, removing and installing again does the right thing (for me, using `vim-plug`). If it still does not create the submodule, pleas run a `git submodule init` and `git submodule sync` on your `iron.nvim`.  It should suffice.

If it still does not create the submodule, we're in serious trouble.

Cheers

**Comment by jduc** [comment]
:( outch, serious trouble it is... I'm also using vim-plug, I tried removing the iron.vim directory in the `plugged` folder and then `:PlugInstall` - still the same error. I also tried syncing the submodule as you suggested, still same error. 

In the iron.vim directory, it seems the zen pluggin is there, pointing to `../../../deps/zen.nvim/src` which contains the ui.py . Am I missing something, like a python lib ? Or could this be related to python3.6 ? Any other ideas ? Thanks a lot.

**Comment by hkupty** [comment]
I just found the bug.
`master` should be fixed by now.

Please test to see if it works for you.

Cheers

**Comment by jduc** [comment]
Everything works like a charm, well done and thank you very much!

**Comment by hkupty** [comment]
No problem! I'm really glad it works now!

Please keep on opening issues in case you find anything!

**Comment by 10b14224cc** [comment]
For those coming from Google, the new way to send visual selection to the REPL is to use [core.visual_send](https://github.com/Vigemus/iron.nvim/blob/7f876ee3e1f4ea1e5284b1b697cdad5b256e8046/lua/iron/core.lua#L395).

Here is an example mapping:
```
vim.keymap.set(
    "v",
    "<leader>il",
    ":lua require('iron.core').visual_send()<CR><Esc>"
)
```
