### ISSUE TITLE
Iron memory management 

### ISSUE THREAD

**Issue by drusmanbashir** [hkupty/iron.nvim#205]
Hi I am trying to configure iron so it only opens a singleton python repl for every python file anywhere. I do not know the correct key/value and where to put it in my iron.lua settings file. I have tried a number of variations including (in a separte line):
```
iron.memory_management='singleton'
```
or by passing a key to set_config like so:

```
iron.core.set_config {
  manager = 'singleton',
  preferred = {
    python = "ipython",
    clojure = "lein"
  },
  repl_open_cmd='to 25 split',
}
```
and 
```
iron.core.set_config {
  manager = 
    {singleton=true},
  preferred = {
    python = "ipython",
    clojure = "lein"
  },
  repl_open_cmd='to 25 split',
}

```
but iron opens multiple repls for different .py files regardless

**Comment by hkupty** [comment]
Hi!

sorry for taking long to answer. I think iron needs desperately a tweak in its documentation as it is clearly not obvious how to configure some things.

The scopes are actual functions so the proper way to configure this is by setting
```
iron.core.set_config {
  scope = require("iron.scope").singleton,
...
}
```

Let me know how that goes.
I'll make sure to update the docs in the upcoming release so things like this are clearer.

**Comment by drusmanbashir** [comment]
That worked! Thank you so much.

**Comment by drusmanbashir** [comment]
May I add what may be a feature request: It would be amazing if there was a way to query a variable that lives inside the repl, from vim and get its overview in a pop-up. Like i have some large python dictionaries and printing them out inside the repl makes me lose overview of them. It would be great to have an option of a pop-up balloon could open showing a tree-like overview of the components of the variable (Vimspector does that). If you think that's out of the original scope of this plug-in could you provide a starting point for those who wish to implement this feature in their copies.
Thanks again!

**Comment by hkupty** [comment]
I'm really flattered to know I can help people's workflow improve w/ iron and, honestly, that's what keeps me maintaining it.
Personally, I've moved away from python and scala, which were the original motivations for iron.nvim. For clojure, I've created acid.nvim, which kind of does the same thing, but it does so through a socket connection to a repl server, so I don't find myself using iron as much these days..

This feature you're requesting was what actually drove me to create acid and I'm not super sure if python/ipython - or any other repl really - do provide a socket-based communication port so iron could interact and get metadata about what is being evaluated in the repl.

The "dirty" alternative would be to interfere with the user session, sending commands to the same terminal and parsing the results. Honestly, I'm not super sure I like that.

But I'll definitely look out for ways to achieve that as of course it would be an invaluable addition to iron and, as a consequence, to your and other people's workflow.

**Comment by hkupty** [comment]
Also, I forgot to mention, I'm trying to rework the internals of iron with #206. After that, new features will likely be easier to add.

**Comment by drusmanbashir** [comment]
Sockets etc.. are all beyond me! I do know that IDLEs like pycharm allow this kind of functionality of course. The quick-dirty hack you suggested seems  like something I might be able to pull off though. I think, with this added piece of functionality will make neovim the best tool for python.
Thanks again and goodluck with acid!
