### ISSUE TITLE
Scheme language REPLs

### ISSUE THREAD

**Issue by mbakhterev** [hkupty/iron.nvim#21]
Please, add some repl configs for scheme (Guile for instance). Or, please, write the instruction about adding new repls by hand. I'am stupid enough to not making Guile to work with iron

**Comment by hkupty** [comment]
Hi!

That should be no problem.. All I need to know is the executable so I can summon the repl as a terminal buffer for neovim. More customizations can be done later.

Also, I'll try to right up some guides on how to create repl providers and other stuff.

Cheers,

**Comment by hkupty** [comment]
I'll close this issue for now. If the scheme repl is not working correctly for you, please reopen this issue.

Cheers.
