### ISSUE TITLE
`visual_send` and `send_motion` break on some special characters

### ISSUE THREAD

**Issue by jakubkaczor** [hkupty/iron.nvim#217]
Minimal working example with IPython. It also happens with R's interpreter. I haven't tested with others.
``` python
a = "abć"
```
`send_line` works as expected, but `visual_send` and `send_motion` result in the following.
``` python
In [3]: a = "abć
  Input In [3]
    a = "abć
        ^
SyntaxError: unterminated string literal (detected at line 1)
```

**Comment by hkupty** [comment]
Thanks for reporting and providing a test. I'll try to have a look at it later today or at the very least until Wednesday.

**Comment by hkupty** [comment]
Sorry for the long delay. I've tested my new branch on this and it certainly doesn't fail. I guess this is a sign I should merge v3.0 soon.

**Comment by jakubkaczor** [comment]
Thank you for your reply. I repeated the tests on the new master (v3.0) and `visual_send` works, but `send_motion` still—doesn't. I start with
```
:IronRepl
```
Having
``` python
a = "abć"
```
in the file, I run the following command.
``` lua
:lua require("iron.core").run_motion("send_motion")
```
Then, I press ap (around paragraph), what results in
```
In [1]: a = "abć
  Input In [1]
    a = "abć
        ^
SyntaxError: unterminated string literal (detected at line 1)
```
`repeat_cmd`, also, doesn't work, even if `visual_send` or `send_line`—which work—are repeated instead of `send_motion`.

**Comment by hkupty** [comment]
I think i found the issue. Would you mind trying out the branch of the PR #221?

**Comment by jakubkaczor** [comment]
No, I don't mind. I've checked, and the changes solve the issue on my side. Thank you. 😉 I assume you are going to merge it soon, so I'm closing the issue.

**Comment by hkupty** [comment]
I'll merge it straight away then! Thank you very much for opening the issue!
