### ISSUE TITLE
Options to send multiple lines as one block

### ISSUE THREAD

**Issue by AdrienLeGuillou** [hkupty/iron.nvim#218]
In the R console (as well as Radian), if you paste the following lines:

```r
print(1)
stop("error here")
print(2)
```

the `print(2)` call is not executed as the whole block as errored on `stop()`. With `iron.nvim` however, because sending these three lines with `core.visual_send()` send them one by one, the error occur, then `print(2)` is executed.

Is there a way to send multiple lines in this fashion? If not I could try and implement that at some point.

Thanks

**Comment by hkupty** [comment]
Hi @AdrienLeGuillou. Thanks for the issue.

Some repls support something called bracketed paste. I think we have that implemented only for ipython and ptpython. I can definitely have a look if R/Radian support bracketed paste and, if so, then adding support might be as simple as mirroring what has been done for ipython/ptpython.

Best regards,
Henry

**Comment by hkupty** [comment]
In fixing #229 I extracted bracketed paste from ipython.  I don't have any experience with R/Radian, but I can try to test locally to  check whether support that support for bracketed paste exists in them and if it works correctly. I'll likely pull an experimental branch for this  and ask you to test further if thats ok.

**Comment by AdrienLeGuillou** [comment]
Thanks a lot!
I just updated my config to match the latest updates. 
Looking at #229 I tested:

```
         repl_definition = {
            r = {
              command = { "radian" },
              format = require("iron.fts.common").bracketed_paste
            },
```

as my REPL definition and it works like a charm!

I'll gladly test experimental branches!

**Comment by hkupty** [comment]
Really glad to hear that!

I'll keep the issue open until I come up with the PR

**Comment by AdrienLeGuillou** [comment]
Hi,
I just tested the updated definition of radian from PR #257. It works perfectly.

Actually, it also work with base R. I can make a quick PR defining R the same way if you'd like

```
r.R = {
    command = { "R" },
    format = bracketed_paste
}
```

**Comment by hkupty** [comment]
I've merged a PR now for R as well.. Should be good to go :)

Let me know if this fixes the issue or feel free to reopen the issue if something is missing

Best regards,
Henry

**Comment by AdrienLeGuillou** [comment]
It works perfectly!

Thanks a lot
