### ISSUE TITLE
Keymaps are being set

### ISSUE THREAD

**Issue by b3nj5m1n** [hkupty/iron.nvim#222]
I'm using the following configuration:
```lua
    use {
        'hkupty/iron.nvim',
        config = function()
            local iron = require("iron.core")
            iron.setup {
                config = {
                    should_map_plug = false,
                    scratch_repl = true,
                },
                keymaps = {}
            }
        end,
    }
```

It's my understanding that this should result in no keymaps being set by iron.nvim. However, according to _:nmap_, the following keymaps are set by iron:
```
n  cl            <Plug>(iron-clear)
n  cq            <Plug>(iron-exit)
n  cst           <Plug>(iron-interrupt)
n  c<CR>         <Plug>(iron-cr)
n  cp            <Plug>(iron-repeat-cmd)
n  ctr           <Plug>(iron-send-motion)
```

I'd like to set these myself, is this a bug, or this there a way to disable this that I missed?

**Comment by hkupty** [comment]
Damn, i forgot to remove the vim file counterparts. I'll update it shortly

**Comment by hkupty** [comment]
I merged the PR, should be working now. Let me know how it goes and if I should close it. Thanks

**Comment by b3nj5m1n** [comment]
Thank you so much for the quick response, it seems to be working fine now!
