### ISSUE TITLE
Unusual behaviour on opening neovim session containing iron repl

### ISSUE THREAD

**Issue by drusmanbashir** [hkupty/iron.nvim#223]
Hi I just update to the beautiful v3.0 of iron.
However, now when i save a session which already has iron inside it, and reload nvim, only iron appears and the accompanying buffer file (python) is gone. 

I am attaching a gif to clarify this issue. A second issue is that  I cannot send visual commands (screencapture shows that too). If iron could not be saved in the session , that would be a fine solution. I have set 'close_window_on_exit' to true but that doesnt seem to do it.

My settings:

```
local iron = require("iron.core")

iron.setup {
  config = {
    buflisted = false,
    -- If iron should expose `<plug>(...)` mappings for the plugins
    should_map_plug = true,
    -- Whether a repl should be discarded or not
    scratch_repl = false,
    close_window_on_exit = true,
    -- Your repl definitions come here
    repl_definition = {
     python = require("iron.fts.python").ipython,
      sh = {
        command = {"zsh"}
      }
    }
  },
  -- Iron doesn't set keymaps by default anymore. Set them here
  -- or use `should_map_plug = true` and map from you vim files
  keymaps = {
    send_motion = "<space>sc",
    visual_send = "<space>sc",
    send_line = "<space>sl",
    repeat_cmd = "<space>s.",
    cr = "<space>s<cr>",
    interrupt = "<space>s<space>",
    exit = "<space>sq",
    clear = "<space>cl",
  }
}

```
![Peek 2022-05-18 18-37](https://user-images.githubusercontent.com/5282314/169107570-3e6ab1f9-26aa-4dce-9446-4c3c8ea8d30f.gif)

**Comment by hkupty** [comment]
Hi, @drusmanbashir 

I think this is because the default window now is a float window.

Can you try setting up the `repl_open_cmd` to `botright split 20` (or the relevant size/split) instead of [the function we're using by default now](https://github.com/hkupty/iron.nvim/blob/8eeb7935247c4a0286047d0854bdce9fe345aad4/doc/iron.txt#L202)?

I can definitely revert back to normal splits if that is causing more issues than good.

**Comment by drusmanbashir** [comment]
Sort of better, though it opens a spare repl when loading from session. This was there before the current update
![Peek 2022-05-18 20-15](https://user-images.githubusercontent.com/5282314/169138898-419df4e9-0f0a-4cfc-a3f8-521afb39def5.gif)
:
visual send does not work anymore. I get the error below:
![Screenshot from 2022-05-18 20-18-40](https://user-images.githubusercontent.com/5282314/169139274-c33016fa-b765-46c4-a6c2-3ad7dd09166e.png)

**Comment by hkupty** [comment]
🤔 I'm assuming this is because everything is now kept inside lua, so iron doesn't have the reference to the repl that was re-created - the terminal is there but iron doesn't know about it. Furthermore, it is likely that the job ID is going to be different, so it won't possibly send data to the restored repl...

**Comment by drusmanbashir** [comment]
Is there a way to disable saving iron repl when quitting neovim?

**Comment by hkupty** [comment]
For the other issues:
1. I'm unsure about `<M-...>` bindings, they might be intercepted by the terminal and/or not properly handled by neovim...
2. Which neovim version are you using? Also, can you test against latest merge? I removed the vim file that was likely causing some confusion (i.e. duplicating functions)

**Comment by hkupty** [comment]
I'm not entirely sure how this session/restore thing works. Can you try setting `scratch_repl` to true on your config? This might do the trick - conceptually speaking, neovim shouldn't save a scratch buffer..

**Comment by drusmanbashir** [comment]
No scratch_repl doesnt work. I think i'll find something like an autocommand on windowleave that calls ironclose
I tried  with ctrl. that doesnt seem to work either, i.e.,

```
send_line = "<c-j>",
```

**Comment by hkupty** [comment]
I just tried here and `<C-j>` and it works fine. Which version of neovim are you using?

I'll investigate a way to force clsoe all repls on neovim exit.
The `close_on_exit` option is for closing the window when the process exits (the other way around  😅 )

**Comment by drusmanbashir** [comment]
Latest v8.0 dev version of neovim. Just signed in to say iron-vim along with lsp and treesitter is one of the main reasons i use neovim as my defacto python idle (i have pycharm pro subscription but only use it for debugger), keep it up!

**Comment by drusmanbashir** [comment]
Just retried with latest neovim version 0.8 dev
Cannot set mod-keybindings.
Still getting the error on visual sebd screenshot above .., Not enough arguments for function: chansend

**Comment by hkupty** [comment]
This seems to correlate with #225. I'll check asap.

**Comment by drusmanbashir** [comment]
This works now. Thank you a lot for fixing this.
