### ISSUE TITLE
Error Using Visual Send with IPython

### ISSUE THREAD

**Issue by xllvrr** [hkupty/iron.nvim#225]
OS: Arch
Nvim Version: 0.7.0-3
Python Version: 3.10.4
IPython Version: 8.3.0

Issue: When using visual send, following error appears:
```
E5108: Error executing lua: ...m/site/pack/packer/start/iron.nvim/lua/iron/lowlevel.lua:165: Vim:E119: Not enough arguments for function: chansend
stack traceback:
        [C]: in function 'nvim_call_function'
        ...m/site/pack/packer/start/iron.nvim/lua/iron/lowlevel.lua:165: in function 'send_to_repl'
        .../nvim/site/pack/packer/start/iron.nvim/lua/iron/core.lua:211: in function 'send'
        .../nvim/site/pack/packer/start/iron.nvim/lua/iron/core.lua:338: in function <.../nvim/site/pack/packer/start/iron.nvim/lua/iron/core.lua:337>
```

Config:
```
local iron = require('iron')

iron.core.setup {
    config = {
        -- Highlights the last sent block with bold
        highlight_last = "IronLastSent",
        -- If iron should expose `<plug>(...)` mappings for the plugins
        should_map_plug = true,
        -- Whether a repl should be discarded or not
        scratch_repl = true,
        -- Automatically closes the repl window on process end
        close_window_on_exit = true,
        -- Your repl definitions come here
        repl_definition = {
            sh = {
                command = { "zsh" }
            },
            python = require("iron.fts.python").ipython
        },
        -- Repl position
        repl_open_cmd = require("iron.view").curry.right(80),
    },
    -- Iron doesn't set keymaps by default anymore. Set them here
    -- or use `should_map_plug = true` and map from you vim files
    keymaps = {
        send_motion = "<space>sc",
        visual_send = "<space>sv",
        send_line = "<space>sl",
        repeat_cmd = "<space>s.",
        cr = "<space>s<cr>",
        interrupt = "<space>s<space>",
        exit = "<space>sq",
        clear = "<space>cl",
    }

}

```

**Comment by hkupty** [comment]
Hi @xllvrr ,

I'm sorry, I can't really reproduce your issue. Can you send data to the repl with either `:IronSend python <some code>` or through a motion with `<space>scap`, for example?
Also, in which condition does it happen? Is it with the repl open already?

In my local tests visual send is working fine, so if I can get any hint to reproduce I can debug and try to figure it out.

**Comment by f3fora** [comment]
I managed to reproduce this issue, which happens also for all other `send`s.

1. Send something to REPL.
2. Go to REPL window and somehow close it (e.g. with `interrupt` or `exit`), without quitting nvim.
(Sometimes this happens also closing the terminal window with :q, sometimes not. I do not understand why sometimes happens.)
3. Send again something. -> Error

I think the REPL should be restarted.

**Comment by xllvrr** [comment]
Hi @hkupty 

Thanks for the prompt reply. I can send individual lines using <space>sl which is the send_line command. I'm not sure why specifically visual send isn't working either. The <space>sc for send_motion is also working. It seems to just be visual_send for me.

**Comment by hkupty** [comment]
Thanks for reply, @xllvrr and for the extra information @f3fora .

I'll debug it here and try to come up with a fix.

**Comment by xllvrr** [comment]
:+1: Iron has been a lifesaver with regards to using Python so I really look forward to these small things being fixed. Thanks very much for your hard work!

**Comment by hkupty** [comment]
I was almost giving up because I couldn't find the reason, until I found this:
![image](https://user-images.githubusercontent.com/2695819/169399531-223fdcd5-2357-4285-b731-d0f4105158c8.png)


I assume there's something wrong in the function that handles formatting for ipython, because it wasn't showing up in my normal test (using just `python`).

**Comment by xllvrr** [comment]
The new update works! Thanks very much for the fix and your hard work!
