### ISSUE TITLE
Error sending motions

### ISSUE THREAD

**Issue by GCBallesteros** [hkupty/iron.nvim#226]
Hi,

Thanks for taking the time to keep on improving iron. I just upgraded to v3.0 and I'm having problems sending motions. To setup I open nvim, do a vsplit and open a repl with IronReplHere. When I try to send a motion I get the following error:

```
E5108: Error executing lua [string "v:lua"]:1: attempt to index field 'iron' (a nil value)
stack traceback:
        [string "v:lua"]:1: in main chunk
Press ENTER or type command to continue
```

I see the issue sending both custom motions and vim inbuilts like `w` or `_`

My config is as follows:
```
-- Iron.nvim config
local iron = require("iron.core")

iron.setup {
  config = {
     -- If iron should expose `<plug>(...)` mappings for the plugins
     should_map_plug = false,
     -- Whether a repl should be discarded or not
    scratch_repl = true,
     -- Your repl definitions come here
     repl_definition = {
       python = {
         command = {"ipython"}
       }
     }
   },
  keymaps = {
     -- set it to old iron default so I don't have to change my init.vim
     -- I get the same error with suggested new mappings
     send_motion = "ctrih",
     -- visual_send seems to be working fine
     visual_send = "<space>sc",
   }
 }
```

Nvim version:
```
NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3
```

**Comment by hkupty** [comment]
Hi @GCBallesteros,

I've tested it locally here with your mapping and it did work. Note that `send_motion` should be the prefix, so `ctrih` for the whole paragraph would be `ctrihap`, for example.
Having that said, I'm puzzled by the error you're getting, as there is nowhere in the code where I call `iron` directly, only `iron.core` or `iron.lowlevel`, for example. I guess it might be something related with [this function, in the old iron.vim file](https://github.com/hkupty/iron.nvim/pull/224/files#diff-d148f6a75f7dd6cce6e5caf30a9df9d467fa0dcd130662955e927585a6216c63L7-L9) that was removed yesterday. Can you try updating again just to be sure you're with a fresh version?

Best regards,
Henry

**Comment by GCBallesteros** [comment]
Yeah, that's how I was using it. I'm on commit `a849de9287`, the commit message reiterates  what you are saying above. I will try to dig a bit futher myself and come back once I have something.

**Comment by GCBallesteros** [comment]
I narrowed it down to this line
https://github.com/hkupty/iron.nvim/blob/f02652ea06dbd5d497f7814f4c3ecbe112039a62/lua/iron/core.lua#L414

Attempting `:lua print(vim.inspect(package.loaded.iron))`  returned `nil` while just inspecting `package.loaded` returned many hundreds of lines into a less like pager. I couldn't figure out how to run a search over it or pipe it out to a file.

**Comment by hkupty** [comment]
Interesting.. I don't know why it's behaving inconsistently, but I know how to fix. I'll try to post a patch for this in the next few hours

**Comment by hkupty** [comment]
Feel free to reopen the issue if it still persists.

**Comment by GCBallesteros** [comment]
Works like a charm

**Comment by drusmanbashir** [comment]
@GCBallesteros Btw, I am using your fantastic blog post in making iron work with jupyter. As of the latest update, the ctrih mappings no longer work for me , to send a jupyter cell en-blocke.  Have you figured a way out of that? Thanks.

**Comment by GCBallesteros** [comment]
@drusmanbashir  Will update the blog soon(-ish). Right now the following config is working for me. On the Lua side I have:
```lua
local iron = require("iron.core")

iron.setup {
  config = {
     -- If iron should expose `<plug>(...)` mappings for the plugins
     should_map_plug = false,
     -- Whether a repl should be discarded or not
    scratch_repl = true,
     -- Your repl definitions come here
     repl_definition = {
       python = {
         command = {"ipython"},
        format = require("iron.fts.common").bracketed_paste
       }
     }
   },
  keymaps = {
     -- set it to old iron default so I don't have to change my init.vim
     -- I get the same error with suggested new mappings
     send_motion = "<space>sc",
     -- visual_send seems to be working fine
     visual_send = "<space>sc"
   }
 }
```

The bracketed_paste part takes care of sending the motion as a block rather than line by line.

On my init.vim I have the following line:
```vimscript
nmap ]x <space>scih]h<CR><CR>
```

If this is still not working feel free to open an issue on https://github.com/GCBallesteros/.personal_dotfiles, which still has the old config that doesn't work with IronV3.
