### ISSUE TITLE
Can't run `IronRepl`

### ISSUE THREAD

**Issue by danjenson** [hkupty/iron.nvim#230]
Just updated to latest commit... but cannot get REPL to start; to repro:

1. `:Packerload iron.nvim`
2. `:IronRepl` returns `Not an editor command`

**Comment by hkupty** [comment]
Hi @danjenson 

You need to initialize iron using the `setup` function in `iron.core`.

Take a look at the readme file for a reference.

Let me know if you need further assistance

**Comment by danjenson** [comment]
thanks, now I'm having problems sending from ipython but I'll create a new issue

**Comment by sdavidsson90** [comment]
I am facing the same issue, and the suggested solution is a little unclear to me. I am using lazy.nvim as my package manager.
