### ISSUE TITLE
Pasting visual blocks doesn't maintain spacing

### ISSUE THREAD

**Issue by danjenson** [hkupty/iron.nvim#231]
When I try to visually highlight and send a function to ipython I get this
![image](https://user-images.githubusercontent.com/4793438/169429194-13cb674d-8a63-4145-a022-9dec45025ce7.png)

My config
```lua
local present, iron = pcall(require, "iron")
if not present then
	return
end

iron.core.setup({
	config = {
		repl_open_cmd = "topleft vertical split",
		should_map_plug = false,
		repl_definition = {
			python = {
				command = { "ipython" },
			},
		},
	},
	keymaps = {
		send_motion = "<leader>l",
		visual_send = "<leader>l",
		repeat_cmd = "<leader>l.",
	},
})

vim.api.nvim_set_keymap("n", "L", ":IronRepl <CR>", {
	noremap = true,
	silent = false,
})

**Comment by hkupty** [comment]
🤔
I think this might have something to do with bracketed paste. Can you try replacing your python repl, in the config, instead of `{ command = {"ipython"} }` for `require("iron.fts.python").ipython`?

**Comment by danjenson** [comment]
That fixed it!
