### ISSUE TITLE
<plug> mappings no longer work

### ISSUE THREAD

**Issue by drusmanbashir** [hkupty/iron.nvim#234]
Hi,
I suspect this is related to change in syntax. I had <plug> mappings in my vim files , for example:
```
vim.cmd[[nmap <space>ss<Plug>(iron-send-line)j]]
```
These no longer do anything.
Thanks

**Comment by hkupty** [comment]
Hi @drusmanbashir 

I'll test `<Plug>()` mappings here again, but I suspect this might not be related to iron. Can you try replacing your `vim.cmd` blocks for `vim.keymap.set`? Like `vim.keymap.set("n", "<space>ss", "<plug>(iron-send-line)")`?

Also, it can be that those mappings to `<plug>()` are not needed anymore and one can use iron api to map straight to the lua functions, by adding the `keymaps` key to the `setup{}` function:

```lua
local iron = require("iron.core")

iron.setup{
  -- config...
  keymaps = {
    send_line = "<space>ss",
  }
}
```
