### ISSUE TITLE
Unable to open repl for ..anything

### ISSUE THREAD

**Issue by danjenson** [hkupty/iron.nvim#239]
![image](https://user-images.githubusercontent.com/4793438/169630709-281fe465-32d2-403b-91a3-d290387fc7d8.png)
I ran `:IronRepl` and then it said it didn't know the file type, but `set filetype` returns `filetype=r` 

My config:
```lua
local present, iron = pcall(require, "iron")
if not present then
	return
end

iron.core.setup({
	config = {
		repl_open_cmd = "topleft vertical split",
		should_map_plug = false,
		repl_definition = {
			python = require("iron.fts.python").ipython,
			r = { command = "radian" },
		},
	},
	keymaps = {
		send_motion = "<leader><leader>",
		visual_send = "<leader><leader>",
	},
})

vim.api.nvim_set_keymap("n", "L", ":IronRepl <CR>", {
	noremap = true,
	silent = false,
})
```

**Comment by milanglacier** [comment]
same question here.

**Comment by milanglacier** [comment]
I find that because `args.fargs[1]` is `''` which is not a nil value.
https://github.com/hkupty/iron.nvim/blob/89f0c3fdcf09243739dcfc400542bd6e79319d9d/lua/iron/core.lua#L382

**Comment by petergi** [comment]
I too am experiencing the same issues. For any Language. Not just R.

**Comment by milanglacier** [comment]
for people who have problem in the v3.0, before the author make a change, add to here solve the issue:

https://github.com/hkupty/iron.nvim/blob/89f0c3fdcf09243739dcfc400542bd6e79319d9d/lua/iron/core.lua#L382

```lua
 local ft = opts.fargs[1] ~= '' and opts.fargs[1] or ll.get_buffer_ft(0) 

```
