### ISSUE TITLE
Cannot use fixed window for REPL buffer(global status line is hided and the window height/width cannot be easily adjusted by mouse dragging / keymapping)

### ISSUE THREAD

**Issue by milanglacier** [hkupty/iron.nvim#240]
currently there are some bugs I find in the code

https://github.com/hkupty/iron.nvim/blob/89f0c3fdcf09243739dcfc400542bd6e79319d9d/lua/iron/core.lua#L382

here `opts.fargs[1]` will return `''` which is not nil, so the filetype of current buffer will never pass, I change it to `opts.fargs[1] ~= ''`.

https://github.com/hkupty/iron.nvim/blob/89f0c3fdcf09243739dcfc400542bd6e79319d9d/lua/iron/core.lua#L486

this one should be `pairs` not `ipairs`

after change the two following, I am able to successfully launch the REPL window, but the REPL window is weird

<img width="1421" alt="Screen Shot 2022-05-22 at 16 42 48" src="https://user-images.githubusercontent.com/45728125/169715050-e006071a-70cf-45ab-abdf-58d735fe502d.png">

Here you will find that the window height cannot be adjusted by mouse dragging, and the global statusline is shadowed
(I am using `set laststauts = 3`).

I find this is because the window now is not a fixed window but a float window.

This thing is really a breaking change, floating window is a bit strange for a REPL use, float window should be a window to be discarded immediately for one-time usage, which may be not ideal for a REPL window.

In general, we are constantly adjusting the height/width of the REPL window such that we can inspect the output more comfortable / edit the codes more comfortable depending on the situation, which is not possible for float window.

Currently the deprecated iron.view.openwin is not compatible with the new API of repl_open_cmd, for the option
`iron.config.repl_open_cmd = require('iron.view').openwin 'belowright 15 split'` like in the older version,
with comlains on expected lua number.

We should not make the fixed window way to be deprecated. Or at least provide a way to make the window be a fixed window. It is also rarely to see that the REPL console is in a float window in other IDE/Editors like vscode and IDEA.

my config:

```lua


    local iron = require 'iron.core'
    local mypath = require 'bin_path'

    local radian_config = require('iron.fts.r').radian
    local python_config = require('iron.fts.python').ipython
    radian_config.command = { mypath.radian }
    python_config.command = { mypath.ipython }

    iron.setup {
        config = {
            should_map_plug = true,
            scratch_repl = true,
            repl_definition = {
                r = radian_config,
                rmd = radian_config,
                python = python_config,
            },
            repl_open_cmd = require('iron.view').openwin 'belowright 15 split',
        },
    }

    keymap('n', '<localleader>rs', '<cmd>IronRepl<CR>', {})
    keymap('n', '<localleader>rr', '<cmd>IronRestart<CR>', {})
    keymap('n', '<localleader>ri', '<Plug>(iron-interupt)', {})
    keymap('n', '<localleader>rc', '<Plug>(iron-clear)', {})
    keymap('n', '<localleader>rq', '<Plug>(iron-exit)', {})

    keymap('n', '<localleader>ss', '<Plug>(iron-send-line)', {})
    keymap('n', '<localleader>s', '<Plug>(iron-send-motion)', {})
    keymap('v', '<localleader>ss', '<Plug>(iron-visual-send)', {})

    keymap('n', '<localleader>sc', [[<LocalLeader>si<Leader>c]], {
        desc = 'iron send a code chunk',
    })

```

the error is

```
Error detected while processing /Users/northyear/.config/nvim/init.lua:
E5113: Error while calling lua chunk: ...hare/nvim/site/pack/paqs/opt/iron.nvim/lua/iron/view.lua:11: Expected Lua number
stack traceback:
[CT: in function
"nvim_set_current_buf"
..hare/nvim/site/pack/pags/opt/iron.nvim/lua/iron/view.lua:11:in function
'openwin'
/Users/northyear/.config/nvim/lua/conf/cli_tools.lua:64:in function
'iron'
/Users/northyear/.config/nvim/lua/conf/cli_tools.lua:177:in main chunk
[C]: in function
'require'
/Users/northyear/.config/nvim/lua/load_configs.lua:11:in main chunk
[CT: in function
'require'
/Users/northyear/.config/nvim/init.lua:5: in main chunk
```

**Comment by milanglacier** [comment]
I find that this is because the opened float window is a floating window?
I don't think this is a wise idea, floating window is so strange for a REPL use, float window should be a window to be discarded immediately for one-time usage, which is definetely not ideal for a REPL window.

**Comment by milanglacier** [comment]
Currently the deprecated `iron.view.openwin` is not compatible with the new API of `repl_open_cmd`, for the option
`iron.config.repl_open_cmd = require('iron.view').openwin 'belowright 15 split'` like in the older version, I think this is not a wise idea. We should keep the open win be a fixed window rather than float window by default

**Comment by milanglacier** [comment]
change the config to 

```
repl_open_cmd = 'belowright 15 split',
```

solves the issue.

However, I think the fixed window way `open_win()` shouldn't be deprecated, unless we have provided another similar way to `view.curry(xxxx)` which sets the repl window to fixed window

**Comment by hkupty** [comment]
Hi @milanglacier 

Thanks for the issue.

I'd like to point out that iron is a project that I develop on my scarce spare time and I'm making an immense effort to make it as good as possible, keeping up with the newest neovim improvements. With that said, just a friendly reminder to moderate the tone when opening up issues on open source projects - I don't consider polite to spam "I don't think it's wise" and state "The new version is buggy" in the issue description.

Github has a "discussions" section and I'd be more than welcome to open up a debate on whether the users of neovim prefer a float or not as a default.

Also, given that some of the issues you faced you already found a fix, I wouldn't mind a pull request to spare me the work of copy-pasting the solution you found - it would also be friendlier.

I don't mind fixing issues and it truly makes me happy to improve iron and, as consequence, improve people's lives, but please bear in mind that the internet is just an interface we use to talk to real people. Even though unusual, manners are still not deprecated.

I'll open a PR to fix the issues you mentioned later on today, if my time permits.

**Comment by milanglacier** [comment]
Hi! I am sorry for my words using and mismanner for describing my functions at initial.  When everything suddenly broke I just got too frustrated to express my mood in a negative way. After thinking my words may be inappropriate, I change my titles and usages. I am sorry for my words again.

The reason why I didn’t submit a PR is, at that time I found that the window behavior is weird (I didn’t notice that it’s a float window by then, so I don’t know for sure if my change for the command args is correct)

anyway the new version is good, now we can send code to REPL when the REPL window is not open! Good job! Thanks for your time and work for this project!

**Comment by milanglacier** [comment]
I will submit a PR for the docs for people who might thinking the window behavior as unexpected.

**Comment by hkupty** [comment]
Thanks for the reply, @milanglacier.

I can completely understand the frustration and that is why I'm trying my best to put extra effort into polishing iron after this big release. There were a lot of under-the-hood improvements but at the same time it was really difficult to keep track of everything since the test suite is broken - soon to be fixed.

Also, I want to clarify that I haven't settled that floats are better or worse than normal splits and that is up for discussion.
Given that repl windows are toggleable by default and I really look to make the most use of my display's real estate, I felt it made sense to have them as floats (covering a considerable part of my display) when I want them focused and closed (but still running) when I want to focus on something else. If that is an unusual use-case, I can definitely change the default to the splits again, but, again, let's have a "Discussions" item for this which - supposedly - would allow for better engagement of the community.

Looking forward to reviewing your PR.

Best regards,
Henry
