### ISSUE TITLE
Expected String or List ... in function 'termopen'

### ISSUE THREAD

**Issue by timoleistner** [hkupty/iron.nvim#241]
Might be correlated to [this](https://github.com/hkupty/iron.nvim/issues/239#issue-1243840832).
If I want to send_line or visual_send in any other filetype than lua, im getting:
```
E5108: Error executing lua: Vim:E475: Invalid argument: expected String or List
stack traceback:
        [C]: in function 'termopen'
        ...m/site/pack/packer/start/iron.nvim/lua/iron/lowlevel.lua:74: in function 'create_repl_on_current_window'
        .../nvim/site/pack/packer/start/iron.nvim/lua/iron/core.lua:30: in function 'create'
        .../nvim/site/pack/packer/start/iron.nvim/lua/iron/core.lua:46: in function 'create_on_new_window'
        .../nvim/site/pack/packer/start/iron.nvim/lua/iron/core.lua:134: in function 'repl_for'
        .../nvim/site/pack/packer/start/iron.nvim/lua/iron/core.lua:199: in function 'send'
        .../nvim/site/pack/packer/start/iron.nvim/lua/iron/core.lua:221: in function <.../nvim/site/pack/packer/start/iron.nvim/lua/iro
n/core.lua:207>
```

My config:
```
local iron = require('iron.core')
iron.setup {
    config = {
        repl_definition = {
            python = 'ipython',
            julia = 'julia',
            sh = 'bash',
        },
    },
    keymaps = {
        send_line = "<space><cr>",
        visual_send = "<space><cr>",
    }
}
```

**Comment by hkupty** [comment]
Hi @timoleistner,

Sounds correct that they're correlated. I'll try to fix this as soon as possible.

Best regards,
Henry

**Comment by timoleistner** [comment]
Somehow the problem persists with another error message:
```
Error executing Lua callback: Vim:E475: Invalid argument: expected String or List
stack traceback:
        [C]: in function 'termopen'
        ...m/site/pack/packer/start/iron.nvim/lua/iron/lowlevel.lua:74: in function 'create_repl_on_current_window'
        .../nvim/site/pack/packer/start/iron.nvim/lua/iron/core.lua:30: in function 'create'
        .../nvim/site/pack/packer/start/iron.nvim/lua/iron/core.lua:46: in function 'create_on_new_window'
        .../nvim/site/pack/packer/start/iron.nvim/lua/iron/core.lua:134: in function 'repl_for'
        .../nvim/site/pack/packer/start/iron.nvim/lua/iron/core.lua:389: in function <.../nvim/site/pack/packer/start/iron.nvi
m/lua/iron/core.lua:388>
```
Also there is a problem with how the terminal is opened with the new recommended way in the docs
`repl_open_cmd = require("iron.view").curry.bottom(40),`
It opens a transparent unfocusable terminal.
![example_term](https://user-images.githubusercontent.com/38843394/169988802-951c636e-f0a5-4e3d-8abb-a6dacc3e0c8e.png)
Some time ago I cobbled together a small function to open a dynamically sized terminal which I thought might be useful as it still opens a focusable terminal :)
```
function Percent_hsplit(percent)
    local current_winheight = vim.api.nvim_win_get_height(0);
    local splitsize = math.floor(current_winheight / 100 * percent);
    return vim.cmd(splitsize .. 'split')
end
```
Usable with `repl_open_cmd = ':lua Percent_hsplit(25)',`
![example_term2](https://user-images.githubusercontent.com/38843394/169990148-b422d8c6-2011-4d0b-a9e3-0cacfe95b7fa.png)

Greetings,
Timo

**Comment by timoleistner** [comment]
https://github.com/hkupty/iron.nvim/blob/4e5285ea6665112a0fa5dca67cdffd6470e16831/lua/iron/lowlevel.lua#L74

This line seems to get a `nil` value with `repl.command`
Changing this to ` local job_id = vim.fn.termopen(repl, opts) ` opens the correct terminal again with `:IronRepl`
send_line and visual_send now throw this error though:
```
E5108: Error executing lua: ...m/site/pack/packer/start/iron.nvim/lua/iron/lowlevel.lua:145: bad argument #1 to 'format' (stri
ng expected, got table)
stack traceback:
        [C]: in function 'format'
        ...m/site/pack/packer/start/iron.nvim/lua/iron/lowlevel.lua:145: in function 'send_to_repl'
        .../nvim/site/pack/packer/start/iron.nvim/lua/iron/core.lua:201: in function 'send'
        .../nvim/site/pack/packer/start/iron.nvim/lua/iron/core.lua:221: in function <.../nvim/site/pack/packer/start/iron.nvi
m/lua/iron/core.lua:207>
```

**Comment by hkupty** [comment]
Ahh, I got what is the issue. In your config, you set `repl_definition` to a string. The repl definition requires a table with a `command`, and that is so because some repls take multiple arguments or have special format properties, like bracketed paste support (i.e. #233). The bundled definition for `ipython` comes with bracketed paste support, for example. 
To fix this then, from you configs, consider replacing the lines below 
```diff
5,7c5,7
<             python = 'ipython',
<             julia = 'julia',
<             sh = 'bash',
---
>             python = require('iron.fts.python').ipython,
>             julia = require('iron.fts.julia').julia,
>             sh = require('iron.fts.sh').bash,
```

**Comment by timoleistner** [comment]
Yes this solved it :)
Thanks for the explanation too!
