### ISSUE TITLE
Missing comma in configuration file readme example

### ISSUE THREAD

**Issue by EMPAT94** [hkupty/iron.nvim#252]
Hello!

I copy-pasted the code [https://github.com/hkupty/iron.nvim#how-to-configure](https://github.com/hkupty/iron.nvim#how-to-configure) here into my local config and it wouldn't work. Found that there is a comma missing:

```lua
    repl_definition = {
      sh = {
        command = {"zsh"}
      }
    } -- <=== HERE (line 14)
    repl_open_cmd = require('iron.view').curry.bottom(40),
    -- how the REPL window will be opened, the default is opening
}
```

Thanks for the awesome plugin.

**Comment by hkupty** [comment]
Hi @EMPAT94 ,

Thanks for the issue! I'll fix it as soon as possible!

Glad you like it!

Best regards,
Henry
