### ISSUE TITLE
Support for Janet Lang (and +1 for user provided config)

### ISSUE THREAD

**Issue by EMPAT94** [hkupty/iron.nvim#253]
Hello there,

A fairly new language [Janet](https://janet-lang.org/) I came across recently, a lovely lisp derivative. I went through the iron.nvim source and managed to get it working locally (just added an entry in fts and it started working seamlessly - great work with the code-base there!)

I figured I could add a PR here, but scrolling through the other issues, I found this: [ "Project-local" REPLs / dynamically detecting REPL settings? #195 ](https://github.com/hkupty/iron.nvim/issues/195).

Now, I _could_ make a PR just for Janet, but if the above is in progress, then it would be redundant. Yet reading through the comments, I realized that could take a while due to time constraints and other priorities, quite understandable.

As it so happens, I have some time on my hands. I am not an expert in Lua by any means, but perhaps we can work together to make this happen sooner than otherwise possible?

Cheers!

**Comment by hkupty** [comment]
Hi @EMPAT94,

First of all, thank you very much for the issue and the compliments on the codebase - I try my best to make iron as easy to contribute as possible so this really means a lot.

While I think that issue allows for much greater configurability, I still see value in having a lot of support available out of the box - for the "just works" experience when you install the plugin or when you're faced with a situation where you're using a new language but are already used to having iron in your workflow.

So I would definitely welcome a PR for Janet, which seems to be a really interesting language indeed - I am a fan of lisps also and have worked for quite a few years with clojure.

So for the REPL support there's not much involved. Python is likely the most complete, but being Janet a list it shouldn't need complex formatting support like bracketed paste, for example.

So all we need is a file like `lua/iron/fts/janet.lua` with a repl definition and an entry in `lua/iron/fts/init.lua` requiring that file.

Let me know if you're stuck so I can help you.

Best regards and good luck with the PR,
Henry

**Comment by EMPAT94** [comment]
I have added a PR for Janet repl in #256 

I agree with the "just works" approach. Perhaps I didn't word it well; A user config would be complementary to the pre-defined repl list, for those languages not in present the list. Althought it seems you already have something cooking in that regards, so I'll be cheering from the sidelines.

Oh, do let me know if I bungled up the PR in some way, I'll correct asap. Thank you.

**Comment by hkupty** [comment]
PR was perfect. Thanks a lot!

The next thing will be the providers, which allows users to dynamically select the repl based on used-defined functions.
A default provider - which already is implemented - will ensure languages without previous configuration will match an installed repl an open up something.
