### ISSUE TITLE
Error Calling Lua Chunk

### ISSUE THREAD

**Issue by xllvrr** [hkupty/iron.nvim#258]
OS: Arch
Nvim Version: 0.7.0-3
Expected Behavior: No errors

Actual Behavior: I haven't changed anything with regards to my setup but for some reason when I opened my nvim setup today the following error message appeared

```
Error detected while processing /home/xllvr/.config/nvim/init.lua:
E5113: Error while calling lua chunk: .../nvim/site/pack/packer/start/iron.nvim/lua/iron/core.lua:557: bad argument #1 to 'insert' (table expected, got nil)
stack traceback:
        [C]: in function 'insert'
        .../nvim/site/pack/packer/start/iron.nvim/lua/iron/core.lua:557: in function 'setup'
        /home/xllvr/.config/nvim/lua/plugin/iron.lua:4: in main chunk
        [C]: in function 'require'
        /home/xllvr/.config/nvim/init.lua:13: in main chunk
```

My Iron Setup is as follows:
```lua
---- IRON-REPL ----------------------------------------------------------------
local iron = require('iron')

iron.core.setup {
    config = {
        -- Highlights the last sent block with bold
        highlight_last = "IronLastSent",
        -- If iron should expose `<plug>(...)` mappings for the plugins
        should_map_plug = false,
        -- Whether a repl should be discarded or not
        scratch_repl = true,
        -- Automatically closes the repl window on process end
        close_window_on_exit = true,
        -- Your repl definitions come here
        repl_definition = {
            sh = {
                command = { "zsh" }
            },
            python = require("iron.fts.python").ipython
        },
        -- Repl position
        repl_open_cmd = require("iron.view").curry.right(function()
            return math.ceil(vim.o.columns / 2)
        end),
    },
    -- Iron doesn't set keymaps by default anymore. Set them here
    -- or use `should_map_plug = true` and map from you vim files
    keymaps = {
        send_motion = "<space>sc",
        visual_send = "<space>sv",
        send_line = "<space>sl",
        repeat_cmd = "<space>s.",
        cr = "<space>s<cr>",
        interrupt = "<space>s<space>",
        exit = "<space>sq",
        clear = "<space>cl",
    }

}
```

**Comment by hkupty** [comment]
Hi @xllvrr,

I'm terribly sorry. I shouldn't have rushed something that now I realize is a breaking change.

I'm pushing a "fix" for it, but the actual issue is that I  renamed a mapping, so `repeat_cmd` is now `send_mark`.

The fix I'm pushing will make it more obvious than the cryptic message lua is giving (which makes sense, but requires some context to understand).

**Comment by xllvrr** [comment]
Hi @hkupty
Okay no problems. Glad to know that it's a known issue at least. Look forward to the change. Will be good to get notified once it's done so I can make the update required, otherwise I'm stuck without the functionality for the time being

**Comment by hkupty** [comment]
Can you check with the latest commit - It might pop an ugly deprecation warning, but it should be informative enough to help you migrate. Let me know how it goes.

**Comment by xllvrr** [comment]
```
Error detected while processing /home/xllvr/.config/nvim/init.lua:
E5113: Error while calling lua chunk: .../nvim/site/pack/packer/start/iron.nvim/lua/iron/core.lua:561: attempt to call field 'deprecate' (a nil value)
stack traceback:
        .../nvim/site/pack/packer/start/iron.nvim/lua/iron/core.lua:561: in function 'setup'
        /home/xllvr/.config/nvim/lua/plugin/iron.lua:4: in main chunk
        [C]: in function 'require'
        /home/xllvr/.config/nvim/init.lua:13: in main chunk
```

It doesn't quite seem to clarify what the change required is to be honest but I'll be changing repeat_cmd on my side to see whether that works out

**Comment by xllvrr** [comment]
Changing the `repeat_cmd` to `send_mark` works perfectly but yeah not sure the error is much more clarifying to be honest

**Comment by xllvrr** [comment]
Perhaps. I'm at the latest non-nightly version available to Arch though. Made sure by doing an update just before this

**Comment by hkupty** [comment]
So it's definitely introduced in a recent master version... I'll make sure to wrap it with a function, there are other uses in the codebase that will likely have similar errors..

**Comment by xllvrr** [comment]
Noted with thanks and thanks for the speedy response!
It should be good to close so I'll do so

**Comment by hkupty** [comment]
I'm really glad to help!
