### ISSUE TITLE
`send_motion`, `visual_send` and `send_mark` are sending with wrong end mark

### ISSUE THREAD

**Issue by hereGittyGitty** [hkupty/iron.nvim#268]
Hi,

I was able to observe the following in _Javascript_ (_Node.js_) and _Lua_ (_Lua5.4_) so far, but it probably does affect other languages as well. Given the following _JS_ code:
```js
let listOfNumbers = [2, 3, 5, 7, 11];
console.log(listOfNumbers[2]);
//          |<------------>|
```
What I want to do is send the characters marked with `|<-->|` to the _Repl_.

1. visually selecting`listOfNumbers[2]` and invoking the `visual_send` _keymaps_ (`ctr` in my case) gives me
```
  > listOfNumbers[2]);
  listOfNumbers[2]);
                  ^

  Uncaught SyntaxError: Unexpected token ')'
```
2. placing the cursor between the `()` and using `ctri(` gives me the same error
3. same with `mark_motion`/`mark_visual` and a subsequent `send_mark`.

Hope there is an easy fix for that. Thanks for _iron.nvim_

Have a good one :)

**Comment by ashiklom** [comment]
Confirming that this is also an issue in Python:

```python
print(myvariable)
#     |--------|
```

...sends the following:

```
In [3]: myvariable)
   ...:
```

This is using the REPL definition: `require('iron.fts.python').ipython`.

**Comment by Palpatineli** [comment]
Looks like this bug is from core.lua line 263, basically if the visual selection is one line and doesn't start from the beginning, then the extracted part will go past the selection by b_col - 1. A simple patch would just change line 263 to `lines[last] = vim.fn.strcharpart(lines[last], 0, max_width - b_col + 1)`

**Comment by ashiklom** [comment]
@Palpatineli Thanks! That fix didn't work for me for some reason.

Adding the following relatively simple block to `core.lua` before the `local lines = ...` definition seems to do the trick.

```lua
  -- Simple case: Sending part of one line.
  -- See https://github.com/hkupty/iron.nvim/issues/268
  -- Second conditional here (`e_col <= string.len...`) guards against linewise
  -- visual mode, which results in `e_col` = MAXCOL (a huge number defined in
  -- Vim source code somwhere).
  if (b_line == e_line) and (e_col <= string.len(vim.fn.getline("."))) then
    marks.set{
      from_line = b_line - 1,
      from_col = b_col - 1,
      to_line = e_line - 1,
      to_col = e_col
    }
    return vim.api.nvim_buf_get_text(0, b_line - 1, b_col - 1, e_line - 1, e_col, {})
  end
```

**Comment by Palpatineli** [comment]
yeah your fix definitely works. Alternatively, the (conceptually) easiest fix would be to flip lines 259-264 and lines 254-257.

**Comment by hkupty** [comment]
You guys are amazing! Thanks @hereGittyGitty for the issue, @Palpatineli for the snippet and @ashiklom for the PR!

**Comment by hereGittyGitty** [comment]
❤️🌛

**Comment by hereGittyGitty** [comment]
Thanks a lot for the patch. But I am afraid I have this issue should be reopened once more.From my [issue report](https://github.com/hkupty/iron.nvim/issues/268#issue-1275833261) the `send_motion` and `mark_motion` command still use a wrong end mark.

the `mark_visual` and `visual_send` counterparts work super nicely. :)

@hkupty would you reopen that issue again as I do not have the privileges to do so since you closed it.
