### ISSUE TITLE
[Feature Request] Allow propotional width panel opening

### ISSUE THREAD

**Issue by tristone13th** [hkupty/iron.nvim#281]
When calling `require('iron.view').curry.bottom(40)`, it will start a panel at the bottom with 40 characters height, but we want to make it proportional to the terminal height width, like `require('iron.view').curry.bottom(0.5)` will open a half-height panel, is this possible?

**Comment by hkupty** [comment]
Hi @tristone13th,
This is in the making with the PR I have baking there. I'll make sure to check out for this.

**Comment by hkupty** [comment]
It should be fixed now. The new API allows for fractions, percentages or functions to allow for even more flexible decision making when opening up the windows :)

Sorry for taking long to merge that, vacations got in the way 😅

**Comment by tristone13th** [comment]
> It should be fixed now. The new API allows for fractions, percentages or functions to allow for even more flexible decision making when opening up the windows :)
> 
> Sorry for taking long to merge that, vacations got in the way 😅

Great work!
