### ISSUE TITLE
Draw IronRepl over nvim with purple background

### ISSUE THREAD

**Issue by lirorc** [hkupty/iron.nvim#285]
I'm using nvim v0.8.0-dev. I have opened the repl within st and xterm terminals, and with different languages.
The behaviour is the same, as in the image. The problem started after I updated to iron version 3, I had no problems
before.
![ss](https://user-images.githubusercontent.com/74657909/185147982-28f026df-05a2-4d29-84d4-f44174d8def3.png)

Thanks

**Comment by hkupty** [comment]
I'm assuming this is because the default window changed to be a float window instead of a normal window. I'm changing this back to normal split windows in the next PR

**Comment by hkupty** [comment]
Can you check now if it is fixed?

**Comment by lirorc** [comment]
Fixed it, thanks \(^_^)/
