### ISSUE TITLE
Help configuring after latest stable rewrite

### ISSUE THREAD

**Issue by lf-araujo** [hkupty/iron.nvim#302]
Hi!

Thanks again for this massively useful tool!

I don´t update my neovim often, and only very recently I had to update it and Iron along with it.

I used to set up some keybindings with which_key, but I don't seem to find the correct way to do this now. My previous settings looked like:

```lua
-- Use which-key to add extra bindings with the leader-key prefix
lvim.builtin.which_key.vmappings["d"] = { "<Plug>(iron-send-mark-motion)", "Send visual to REPL" }


lvim.builtin.which_key.mappings["R"] = {
  name = "+REPL",
  r = { "<cmd>IronRepl<CR>", "Start REPL" },
  d = { "<Plug>(iron-send-line)", "Send line" },
  f = { "<cmd>IronFocus<CR>", "Refocus" },
}
```

- Any ideas on how I would successfully adapt these?

Many thanks

**Comment by vhristev** [comment]
Here is my "whichkey" using lua.

```
 p = {
      = name = "Python REPL",
      l = { ":lua require('iron.core').send_line('r')", "Send Line" },
```

For all functions, you can check `:h iron-functions`.
The Function is after the ('iron.core').FUNCTION

**Comment by lf-araujo** [comment]
Thanks, this solves my issues!
