### ISSUE TITLE
newline in string causes execution to fail in radian.

### ISSUE THREAD

**Issue by fisher-j** [hkupty/iron.nvim#304]
When trying to send lines to radian, if there is a newline in a string, it causes strange behavior. The interpreter seems to be stuck waiting for more input. If I break (ctrl-c) then the prompt appears, but pressing <CR> causes last line to be "resubmitted," and the interpreter gets stuck again. 

I tried with and without bracketed paste, and also tried using the windows_linefeed format from iron.fts.python module.

sending strings works with regular R interpreter.

![WindowsTerminal_0KfCtTtNNL](https://user-images.githubusercontent.com/63136705/200412195-ab923fd2-b341-49e0-8aad-8d4688990dda.gif)

I'm using neovim 0.8 with Windows terminal.

**Comment by hkupty** [comment]
Hi, @fisher-j!

This is very weird. I'll try to reproduce locally so I can debug it and I'll let you know. Hopefully something that can be reproduced easily because I don't have any experience w/ R or radian. I'll keep you posted.

**Comment by fisher-j** [comment]
I was about to re-post over at [randy3k/radian](https://github.com/randy3k/radian) and I realized that the problem has somehow self-resolved. I am now able to send multi-line strings with no problem. I'm not sure what the problem was. 
Thanks for working on this integral piece of software.

**Comment by hkupty** [comment]
I'm glad to hear that it sorted itself out!

Thanks for the support, it is in fact only because of the heartwarming feedback of the community that I keep on supporting iron :)

**Comment by kofm** [comment]
I have the same problem :( Which version of Neovim/radian are you using?
