### ISSUE TITLE
How to go back to normal mode in REPL window

### ISSUE THREAD

**Issue by tdyoshida** [hkupty/iron.nvim#305]
Hi, this is probably very basic question, but I couldn't find an answer myself.

After switching to REPL window by IronFocus and start insert mode, I could not figure out the way to go back to normal mode.
Esc or my key binding (jj) do not work, and I could not run any commands (since it just types in in the REPL window).

Thanks for the help!

**Comment by yqwu905** [comment]
May you try `<C-\><C-n>`?
You could map it to any keymap with `tnoremap`.

**Comment by tdyoshida** [comment]
It worked! Thank you so much @yqwu905 !

**Comment by vhristev** [comment]
@tdyoshida 

Here is what im doing i stole it from official doc. https://neovim.io/doc/user/nvim_terminal_emulator.html


vimrc
`:tnoremap <Esc> <C-\><C-n>`

lua
```-- Remap Neovim terminal to exit with <Esc>
map('t', '<Esc>', '<C-\\><C-n>', {noremap = true, silent = false})
```

Some other options are to use another terminal, not the embeded one: https://github.com/kassio/neoterm
