### ISSUE TITLE
Keymaps cause a slew of errors with which-key

### ISSUE THREAD

**Issue by BlueDrink9** [hkupty/iron.nvim#311]
When activating which-key, I get a bunch of dictionary errors in the which-key code that I don't get if I remove my keymaps section.

Do you use nvim-which-key?

**Comment by BlueDrink9** [comment]
Actually, I was using vim-which-key. Resolved this by switching which-key.nvim (which I thought I had already done)

**Comment by meicale** [comment]
Hi, I meet the same problem. How did you solve it? iron exposes fewer commands and lua functions which I can use in which-key, such as “Interupt, clear...". How did you map this keybinding? 
Thanks a lot!

**Comment by BlueDrink9** [comment]
Probably not the same problem. I was using the wrong which-key. I didn't need to manually map anything
