### ISSUE TITLE
Sending text moves cursor

### ISSUE THREAD

**Issue by Alok** [hkupty/iron.nvim#33]
So I type `ctrip` at the end of the line `print(3)` where my cursor is at the end of the line and it moves my cursor to the beginning of the line.

Is it possible to make it not do that?

**Comment by hkupty** [comment]
I did some tests here and it works here. Also, I removed a `normal` command which was messing with registers.

**Comment by Alok** [comment]
You may want to use `winsaveview()` and `winrestview()` instead of a temporary mark, since I (and others presumably) use plugins like signature.vim to show marks, and toggling marks is a bit jarring when your gutter suddenly changes size.

**Comment by hkupty** [comment]
I'll take a look at those... 

Cheers
