### ISSUE TITLE
Feature request: allow more control over the spawned REPL split

### ISSUE THREAD

**Issue by Alok** [hkupty/iron.nvim#34]
So the REPL split is not at all nice looking. It's too large a lot of time as it takes up the bottom half of the screen. I think a better approach would be to allow something like the following. I use GoldenView to get nice splits, but that could be left out.

```vim
    call GoldenView#Split()
    enew | call termopen('python')
```

Slime.vim does this, and gets the terminal jobid to figure out where to send text. I wonder if something equivalent is possible here without a bunch of code.

**Comment by hkupty** [comment]
That should be pretty easy. I'll take a look at it later today. 

Cheers

**Comment by hkupty** [comment]
That is actually already done.
You can try with `let g:iron_repl_open_cmd = "call GoldenView#Split()"`

Please let me know if that worked out for you (I tested here and seems to be working).

**Comment by Alok** [comment]
Worked

**Comment by hkupty** [comment]
Great! Cheers
