### ISSUE TITLE
how to call IronSend?

### ISSUE THREAD

**Issue by Alok** [hkupty/iron.nvim#36]
This may be more an issue with my configuration, but I'm not finding the command `IronSend`. I can access these commands but not any others:

```
IronClearReplDefinition 
IronDumpReplDefinition
IronPromptCommand
IronPromptRepl           
IronRepl
```

I'm using the latest versions of iron.nvim, nvim, neovim-python-client, and I did run `UpdateRemotePlugins`.

**Comment by hkupty** [comment]
`IronSend` is a function. It seemed saner to make it that way. 

Have you tried `:call IronSend("arg")`?

**Comment by Alok** [comment]
It doesn't show up if I do that.

**Comment by Alok** [comment]
So I deleted and regenerated the `rplugin.vim` file. That seemed to fix it.
