### ISSUE TITLE
ptipython: multiline not working

### ISSUE THREAD

**Issue by jduc** [hkupty/iron.nvim#4]
Hey, 
When sending multiple lines on the pyipython REPL (for example `ctr }`), only the first line is interpreted by the ptipython terminal window. Setting the pyipython to paste mode (in the config file, as F6 key is not registered by neovim terminal) I can see that the REPL is receiving all the lines, but only the first one is interpreted. 

Thanks for adding more REPL (R, ptpython etc..) it's really great.

**Comment by hkupty** [comment]
Hi! Thanks for helping iron.nvim to get better! 

I just read quickly that `ptpython` supports bracketed paste. This might help. 

I'll test to see if I can can get that working. 

Cheers!

**Comment by jduc** [comment]
Hello, 

Thanks for fixing this, I gave it a try, it seems to work as the lines are registered in the terminal buffer, but they are not executed. To execute them, I have to jump to the REPL, go in insert mode and type <ENTER>. Is it just me and somehow due to my config ? Thanks!

**Comment by hkupty** [comment]
Just fixed again. That was an issue with how pt{,i}python handles bracketed paste. This should be solved now. Please, feel free to reopen if you still have issues.

Cheers

**Comment by jduc** [comment]
Hey, 
I was out for some time so I could not test until now. Thanks all is working great now. Just one detail that I found, if you try to send code that does not end with an empty line, the code is not executed in the REPL, you need to either send an empty line or move to the terminal and manually type <enter>. 
This happens notably if you try to run the last line of a file with ctrj (with no empty line after) or if you try to run 0ctr$.

**Comment by hkupty** [comment]
I'll take a look at it and see.... Supposedly, this was already fixed... I'll check it
