### ISSUE TITLE
how to cancel command in REPL

### ISSUE THREAD

**Issue by Alok** [hkupty/iron.nvim#40]
sometimes i send input to a python repl and it ends up mangled and i have to switch to the repl buffer and `<c-c>` that input. is there a way to send the `<c-c >` with iron?

**Comment by hkupty** [comment]
I just added two mappings for `<C-c>` and `<C-d>`. They're respectively mapped to `<plug>(iron-interrupt)` and `<plug>(iron-exit)`.

Cheers
