### ISSUE TITLE
remapping iron-send-motion unexpectedly overwrites ctr and nnoremap doesn't work at all.

### ISSUE THREAD

**Issue by cmcaine** [hkupty/iron.nvim#49]
Thanks for the plugin :)

From my init.vim:

````
" Map iron.vim
nnoremap <leader>r <Plug>(iron-send-motion)
vnoremap <leader>r <Plug>(iron-send-motion)
````

If I leave that excerpt in, the `ctr` mapping is not made. This behaviour is not documented.

Worse, my mapping doesn't work. If I make it an `nmap` rather than `nnoremap` mapping, then it works as expected. This is unusual and also not documented.

**Comment by hkupty** [comment]
> Thanks for the plugin :)

I'm glad you like it!

> If I leave that excerpt in, the ctr mapping is not made. This behaviour is not documented.

It seems that this feature is poorly implemented, unfortunately.

I'll take a look at it.

> Worse, my mapping doesn't work. If I make it an nmap rather than nnoremap mapping, then it works as expected.

This is quite unexpected. I'll keep an eye at it while I try to fix it. 

Thanks for the issue! I'll take a look at it later today and try to come up with a better solution. 

Cheers!
