### ISSUE TITLE
Using iron.nvim with Python 3 via Homebrew

### ISSUE THREAD

**Issue by sheriferson** [hkupty/iron.nvim#56]
Hi,

I tried finding an answer for this somewhere but couldn't find it in the documentation or in the open/closed issues:

How can I use iron.nvim plugin with Python 3 as installed by Homebrew instead of the default/built-in Python? The path is `/usr/local/bin/python3`.

I tried `:IronPromptRepl` but I don't think it can do what I want.

Thanks.

**Comment by hkupty** [comment]
I'm terribly sorry about that.

I think I'll have to explicitly describe python3 as a preferred repl over python if it exists in PATH. In the meantime, I'm thinking about a better solition for that.

Thanks for filling in this issue.

Cheers!

**Comment by sheriferson** [comment]
No worries! You put the effort into creating this plugin and putting it out there, so definitely no need to be sorry about a possible missing feature.

So to confirm, that is currently not doable?

**Comment by hkupty** [comment]
If it's in your $PATH, you should be able to run using `IronPromptRepl`, by passing `python3`. 

Now, if that doesn't work, then we have a major bug.

**Comment by sheriferson** [comment]
I do think it's in my $PATH:

```
$ echo $PATH                                                                                                                                                     
[...] /usr/local/bin /usr/bin /bin /usr/sbin /sbin
$ which python3
/usr/local/bin/python3

# edit a python file in neovim
:IronPrompRepl
python3
Unable to find repl for python3
```

For what it's worth, I use fish shell, but I haven't had any other issues related to the path there.

**Comment by hkupty** [comment]
I directed you to the wrong command. Try using `IronPromptCommand`.

`IronPromptCommand` ignores `REPL` definitions and call the command directly.

**Comment by sheriferson** [comment]
Great! That did the trick.
It wasn't entirely clear to me what `:IronPromptCommand` did when I read the documentation.
I might send a pull request later adding this small snippet as an example to README if that's good with you. I can imagine other people might not be clear on how to use Python 3 as the REPL.

Thanks!

**Comment by hkupty** [comment]
No problem!

I'll try to come up with a way to select versions and/or set a preferred so this won't bother much again.
