### ISSUE TITLE
Installation, zen.nvim dependency

### ISSUE THREAD

**Issue by kropper** [hkupty/iron.nvim#59]
When running UpdateRemotePlugins, nvim gives me teh creeps about python module zen.nvim not found. There is 1/2 page of error messages, and after that, nothing works. Is there any step by step installation guide, please?

**Comment by hkupty** [comment]
Not sure how you installed it, but Iron uses zen.nvim as a submodule. Plugin installers usually resolve this, but in case it was missed, sync and update git submodules. If you have downloaded iron.nvim without git, do the same for hkupty/zen.nvim and place it on deps/zen folder. It probably will be enough, since the symlink already points to the correct place. 

Those are several reusable actions for dealing with neovim from python and is required for managing repl windows.

If you still have problems with zen, please come back again. Hope this helps. 

Cheers, 
Henry John Kupty

**Comment by kropper** [comment]
Thanks for the hint. I downloaded zen.nvim and put it into the deps/zen folder. I'mnowstuckwith:

```
Encountered ImportError loading plugin at /Users/kropper/.vim/bundle/iron.nvim/rplugin/python3/iron: cannot import name 'open_term'

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/neovim/plugin/host.py", line 131, in _load
    module = imp.load_module(name, file, pathname, descr)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/imp.py", line 244, in load_module
    return load_package(name, filename)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/imp.py", line 216, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 675, in _load
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
ImportError: cannot import name 'open_term'
remote/host: python3 host registered plugins []
remote/host: generated rplugin manifest: /Users/kropper/.local/share/nvim/rplugin.vim
```

Is there any `open_term` I should download or do I have to provide my own?

**Comment by hkupty** [comment]
It seems like an import error. `open_term` is a function from zen. Probably its still not finding the zen.nvim modules. 

Try changing from `deps/zen` to `deps/zen.nvim`. I just checked the symlink and it it points to `../../../deps/zen.nvim/src`, so that explains why it's still raising import errors.

**Comment by kropper** [comment]
I tried that, and both in parallel, but still no luck. Same error message as before. :-/

**Comment by kropper** [comment]
OK, that error is gone with zen.nvim at fd8a6957cd116a310b88a06d7201505e6755ef51 . However, after UpdateRemotePlugins, none of the commands IronRepl, IronPromptRepl etc. work. Autocompletion offers IronUnwatchCurrentFile and IronWatchCurrentFile only, which are not documented and calling them results in an E216 No such group or event Error. How can I get this to work?

**Comment by hkupty** [comment]
This is weird. Would you mind pasting your `~/.local/share/nvim/rplugin.vim`?

It should have generated Iron command entries there.

**Comment by kropper** [comment]
This is how it looks like:

```
$ cat ~/.local/share/nvim/rplugin.vim
" python3 plugins
call remote#host#RegisterPlugin('python3', '/Users/kropper/.vim/bundle/iron.nvim/rplugin/python3/iron', [
      \ {'sync': v:false, 'name': 'IronClearReplDefinition', 'type': 'command', 'opts': {}},
      \ {'sync': v:true, 'name': 'IronRepl', 'type': 'command', 'opts': {'bang': ''}},
      \ {'sync': v:false, 'name': 'IronDumpReplDefinition', 'type': 'command', 'opts': {}},
      \ {'sync': v:true, 'name': 'IronStartRepl', 'type': 'function', 'opts': {}},
      \ {'sync': v:false, 'name': 'IronSendSpecial', 'type': 'function', 'opts': {}},
      \ {'sync': v:true, 'name': 'IronPromptCommand', 'type': 'command', 'opts': {}},
      \ {'sync': v:true, 'name': 'IronPromptRepl', 'type': 'command', 'opts': {}},
      \ {'sync': v:false, 'name': 'IronSendMotion', 'type': 'function', 'opts': {'range': ''}},
      \ {'sync': v:false, 'name': 'IronSend', 'type': 'function', 'opts': {}},
     \ ])


" ruby plugins


" python plugins

```

**Comment by hkupty** [comment]
They are correct. It should work correctly. 

Try running `:IronRepl` on a file which type is supported. It should work correctly. If it doesn't, feel free to come back again. 

I'll wait for your response to close the issue.

**Comment by kropper** [comment]
thanks, works after reboot =)

**Comment by hkupty** [comment]
Glad to know that it worked! 

Cheers!

**Comment by benignoc** [comment]
I am having the same problem but I do not get it to run, zen.nvim seems to be correctly sitting within deps but for some reason I get the same error. The difference for me is that I do not get to see the list of the possible iron.nvim commands at rplugin.vim ( sitting at AppData\Local\nvim\rplugin.vim not at .local\share\nvim):
_C:\Users\benig\AppData\Local\nvim>cat rplugin.vim
" node plugins

" python3 plugins
call remote#host#RegisterPlugin('python3', 'C:/Users/benig/.local/share/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete', [
      \ {'sync': v:false, 'name': '_deoplete_init', 'type': 'function', 'opts': {}},
     \ ])

" ruby plugins

" python plugins_


Any hints as to what I can do ? I have it installed with vim-plug.
