### ISSUE TITLE
open repl in vsplit instead of horizontal split

### ISSUE THREAD

**Issue by mdgoldberg** [hkupty/iron.nvim#65]
Currently, it seems that running :IronRepl opens up the repl in a horizontal split at the bottom of vim. Is it possible to make the repl open in a vertical split on the right half of vim?

**Comment by hkupty** [comment]
Hi!

I'm terribly sorry that this was left undocumented. I'll fix that.
It is possible to configure the placement of your terminal by defining the parameters on the `iron_repl_open_cmd` variable, such as:
```vim
let g:iron_repl_open_cmd = 'topleft vertical 100 split'
```

I'll try to make things more stable and more documented somewhere next week and I'll surely fill this in.
Thanks for the issue!

Cheers,
Henry

**Comment by mdgoldberg** [comment]
Thanks!
