### ISSUE TITLE
E117: Unknown Function IronSend

### ISSUE THREAD

**Issue by yelled1** [hkupty/iron.nvim#99]
Hi:

After using this extensively for python:
/* Just realized IronSend  no longer works for python either - after I just updated plugin 
   I have read through the README but don't see that change. Just see IronSendSpecial
   and IronSend seems to be still available as a function (according to the doc)
   Also
```iron-send-motion``` that worked below does NOT work for python
I have simple file.py
```
import os
os.path
```
when I use vmap to execute
```
Python 3.6.7 (default, Dec  8 2018, 07:20:50)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 0~
  File "<stdin>", line 1
    0~
     ^
SyntaxError: invalid syntax
>>> import os
>>>
>>> os.path
<module 'posixpath' from '/home/hyoon/.pyenv/versions/3.6.7/lib/python3.6/posixpath.py'>
>>> 1~
  File "<stdin>", line 1
    1~
     ^
SyntaxError: invalid syntax
>>>
```
Don't know where 0~ & 1~ is coming from. I tried with both line number on/off
 */

I have added 
```
autocmd FileType scala map <silent> <leader>, <Esc>`> <C-x>oG<C-x>o
autocmd Filetype scala vmap <buffer> <localleader>\ $<Plug>(iron-send-motion)
autocmd Filetype scala nmap <localleader>\ :call IronSend(getline('.'), &ft)<CR><C-x>o 
autocmd Filetype scala imap <localleader>\ <Esc>:call IronSend(getline('.'), &ft)<CR>
```
to execute scala code.
But when I press <localleader>\
I get 
```E117: Unknown Function IronSend```
Am I missing files or something? I am attempting to use sbt with this:
BTW: I changed
lua/iron/fts/init.lua file
```
  scala = require("iron.fts.sbt"),
```
to use sbt rather than just plain old scala repl & once invoked repl
``` sbt:SparkSql> console ```
to goto scala repl

Also: ```iron-send-motion``` from vmap seems to work well & sends the lines via :paste
```
scala> :paste
// Entering paste mode (ctrl-D to finish)

import org.apache.spark._
import org.apache.spark.SparkContext._

// Exiting paste mode, now interpreting.

import org.apache.spark._
import org.apache.spark.SparkContext._
```

Thank u much & Merry x-mas!

**Comment by hkupty** [comment]
Hi, thanks for the issue and sorry for the mess.

Recently I've changed this plugin to use lua as a backend (since its now embedded into neovim). This also came with some changes in the api and exposed functions.

If you intend to send code directly to the repl through functions, the simples way is to use luaeval as such:

```viml

call luaeval('require("iron").core.send(_A[1],_A[2])", &ft, code)

```

I hope that works and, once again, sorry for the confusion and miscommunication.

I'll probably rework a bit more to make this smoother.

Cheers and happy holidays,
Henry John Kupty

**Comment by yelled1** [comment]
Thank you for responding so quickly. I just decided to spend the holidays to update computer. So, I did not expect to hear back until new years or later.
Let me attempt your solution & hopefully this will work! Be write back.

**Comment by yelled1** [comment]
```
    "autocmd Filetype python nmap <localleader>\ :call IronSend(getline('.'), &ft)<CR><C-x>o "<ESC><C-w>jG<C-w>pj0
    autocmd Filetype python nmap <localleader>\ :call luaeval('require("iron").core.send(_A[1],_A[2])', &ft, getline('.'))<CR><C-x>o "<ESC><C-w>jG<C-w>pj0
    "autocmd Filetype python imap <localleader>\ <Esc>:call IronSend(getline('.'), &ft)<CR>
    autocmd Filetype python imap <localleader>\ <Esc>:call luaeval('require("iron").core.send(_A[1],_A[2])", &ft, getline('.'))<CR>
```
I attempted it, but given my unfamiliarity with both lua & vim, I am a bit lost to where & how to put "code",  which should be getline('.'). Could you help?
Thank you & have a wonderful new years,

**Comment by hkupty** [comment]
What error did you have? I'm unable to test it, but I'd guess it should be something similar to it.

**Comment by yelled1** [comment]
I got: ```E118: Too many argument for function: luaeval```

**Comment by hkupty** [comment]
So the second argument should be a list:

`call luaeval('require("iron").core.send(_A[1],_A[2])', [&ft, getline('.')])`

**Comment by hkupty** [comment]
(sorry, it would've been way easier if I was on a computer, testing before answering)

**Comment by yelled1** [comment]
Ah, that worked, but I get the same unknown problem as before ```0~<CR> import os 1~<CR>``` back from python; however, scala works, which is what I need for the moment. It ```:paste``` all the code even one liners, but that's good enough for now. I suspect that I am not getting issues with ```0~```, as was in python, is that Iron is using the ```:paste``` mode on scala.

**Pls don't worry & take ur time & enjoy the holidays.** I can wait. It's likely have to with some other feature you introduced. So, I would not expect answers until after holidays.
Thank you,

FYI: Below is Python
```python
  File "<stdin>", line 1
    0~
     ^
SyntaxError: invalid syntax
>>> import os
>>> 1~
  File "<stdin>", line 1
    1~
     ^
```
```autocmd Filetype scala imap <localleader>\ <Esc>:call luaeval('require("iron").core.send(_A[1],_A[2])', [&ft, getline('.')])<CR>```
Below is Scala 1st paste is multiple lines & 2nd is one line IronSend with ```getline('.')``` as above.
```scala
scala> :paste
// Entering paste mode (ctrl-D to finish)

import org.apache.spark.sql._
import org.apache.log4j._
import org.apache.spark.mllib.linalg.Vectors
import org.apache.spark.mllib.regression.LabeledPoint
import org.apache.spark.mllib.regression.LinearRegressionWithSGD
import org.apache.spark.mllib.optimization.SquaredL2Updater


// Exiting paste mode, now interpreting.

import org.apache.spark.sql._
import org.apache.log4j._
import org.apache.spark.mllib.linalg.Vectors
import org.apache.spark.mllib.regression.LabeledPoint
import org.apache.spark.mllib.regression.LinearRegressionWithSGD
import org.apache.spark.mllib.optimization.SquaredL2Updater

scala> :paste
// Entering paste mode (ctrl-D to finish)

    Logger.getLogger("org").setLevel(Level.ERROR)

// Exiting paste mode, now interpreting. 
```
**REALLY, I am good for now, as my next project is on scala. **

**Comment by hkupty** [comment]
Glad to know that it's working now! 

Don't worry, this is not ruining the holidays. I'll debug it thoroughly when I'm back, but those answers usually are things that I know by heart or that come up quickly.

Anyway, I'll keep the issue open until I fix the Python version.

If you have any other problems or questions, please let me know. Don't refrain from opening another issue.

I truly appreciate when I know that I'm making my plugins better and that I'm helping out people around the world to be more productive or to have a better experience.

Cheers and happy holidays,
Henry John Kupty

**Comment by yelled1** [comment]
Would b nice to fix this for Python, if you could. Thank u,

**Comment by hkupty** [comment]
I ask you to try after last merge, to check if the error still persists or not.

Thank you very much

**Comment by yelled1** [comment]
It works! Almost perfectly. Only issue was that it seems to create extra carriage return.
Is it impossible to deal with? Nah, but would be nice to not have an extra carriage return at certain point.
Thanks you VERY much,

1st) Visual mode
```
Python 3.6.5 (default, Dec 25 2018, 21:26:50)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pickle
>>> import datetime as dt
>>> import numpy as np
>>> . ##### this is an extra #####
```

2) Sending line by line in both nmap & imap mode
```
>>> import pandas as pd
>>> ### extra
>>> import plotly
>>> ### extra
>>> from plotly.graph_objs import (Layout, Histogram, Scatter, Bar, Figure)
>>>
>>>
```

**Comment by hkupty** [comment]
Hi,

Is this still happening? I'm trying to burn down all the issues this week, as I've been unable to do so properly on the last months.

Please let me know if this still needs some attention.

Best regards,
Henry

**Comment by hkupty** [comment]
I'm going to close this issue, please don't refrain from reopening it or creating a new one if you think it's needed.

Best regards,
Henry
